const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--headless=new']});
const ctx=await b.newContext({viewport:{width:390,height:800},deviceScaleFactor:3});const p=await ctx.newPage();p.errs=[];p.on('pageerror',e=>p.errs.push(e.message));
let puts=[];await p.exposeFunction('logPut',(x)=>{puts.push(x);});
await p.addInitScript(()=>{localStorage.setItem('manuora.welcomed','true');localStorage.setItem('manuora.v','3');localStorage.setItem('manuora.bedHour','0');localStorage.setItem('manuora.cfg',JSON.stringify({name:'Vini',body:'#2E86DE',belly:'#F6F1E7',tattoo:'none',animal:'manu',night:'off',tiare:true}));localStorage.setItem('manuora.code',JSON.stringify('AAAA2222'));localStorage.setItem('manuora.share',JSON.stringify({on:true,name:'T'}));window.fetch=async(u,o)=>{if(o&&o.body)window.logPut(o.body);return {ok:true,json:async()=>null};};});
await p.goto('file:///home/claude/manu-ora-site/index.html');await p.waitForTimeout(1500);await p.evaluate(()=>closeSheet());
const has=()=>p.evaluate(()=>{const c=birdEl.querySelector('.mcloud');return c?c.className:null;});
await p.evaluate(()=>pickRing('oaoa'));console.log('ok emotion',await has());
await p.evaluate(()=>pickRing('__dark'));console.log('dark',await has(),await p.evaluate(()=>!$('#crisis').hidden));await p.evaluate(()=>{$('#crisis').hidden=true;});
await p.evaluate(()=>pickRing('oto'));await p.waitForTimeout(2600);console.log('sad',await has());
await p.evaluate(()=>{bubbleEl.classList.remove('show');if(RING.open)closeRing();});await p.waitForTimeout(3200);
const box=await p.evaluate(()=>{const r=birdEl.getBoundingClientRect();return {x:Math.max(0,r.x-60),y:Math.max(0,r.y-80),width:200,height:180};});await p.screenshot({path:'/home/claude/work/cloud1.png',clip:box});
await p.click('.mcloud',{force:true});await p.waitForTimeout(400);console.log('tap',await p.evaluate(()=>[bubbleEl.textContent.slice(0,40),RING.open,B.state]));
await p.evaluate(()=>bubbleEl.querySelector('[data-m="cloud:ok"]').click());
await p.evaluate(()=>closeBreath(true));await p.waitForTimeout(300);console.log('sun',await has());await p.waitForTimeout(600);await p.screenshot({path:'/home/claude/work/cloud2.png',clip:box});
await p.waitForTimeout(8200);console.log('gone',await has());
console.log('not shared',puts.filter(x=>/cloud|nuage/i.test(x)).length,JSON.stringify(await p.evaluate(()=>myLook())).includes('cloud'));
await p.evaluate(()=>{pickRing('riri');});await p.waitForTimeout(500);await p.evaluate(()=>{cloudTap();bubbleEl.querySelector('[data-m="cloud:off"]').click();});await p.waitForTimeout(2000);
await p.evaluate(()=>pickRing('riri'));await p.waitForTimeout(300);console.log('off',await has(),await p.evaluate(()=>store.get('noCloud')));
console.log('re-enable',await p.evaluate(()=>{setQuiet(false);showTab('bird');const c=$('#cloudOpt');const was=c.checked;c.click();return [was,c.checked,store.get('noCloud')];}));
console.log('auto fade',await p.evaluate(()=>CLOUD_MS));
console.log('errs',p.errs);await b.close();})();
