# Patch "le pāuma (cerf-volant) sur la plage + Te Heiva : le feu, la danse, le bar à jus, les cœurs liés autour du feu".
# Dépend de jeu-patch (moteur canvas) et de dock-patch (icônes). Usage : python3 heiva_patch.py <site>/index.html <manu-ora.html>
import sys
for path in sys.argv[1:]:
    s=open(path,encoding='utf8').read()
    def rep(a,b,n=1):
        global s
        assert s.count(a)==n,(path,a[:70],s.count(a))
        s=s.replace(a,b)
    def rep_opt(a,b):
        global s
        if s.count(a)==1: s=s.replace(a,b)
    assert 'function bkLoop(' in s and 'function dockRender(' in s, 'appliquer jeu-patch et dock-patch avant'
    rep(".pepes{position:absolute;",""".dayscene .hv-fl{transform-box:fill-box;transform-origin:50% 100%;animation:hvFl .55s ease-in-out infinite alternate}
.dayscene .hv-fl2{animation-duration:.42s;animation-delay:-.2s}
@keyframes hvFl{from{transform:scaleY(1) scaleX(1)}to{transform:scaleY(1.2) scaleX(.88)}}
.dayscene .hv-sp{animation:hvSp 1.7s linear infinite;opacity:0}
@keyframes hvSp{0%{transform:translateY(0);opacity:0}12%{opacity:1}100%{transform:translateY(-80px) translateX(10px);opacity:0}}
.dayscene .hv-dance{transform-box:fill-box;transform-origin:50% 100%;animation:hvDance .62s ease-in-out infinite alternate}
@keyframes hvDance{from{transform:translateY(0) rotate(-6deg)}to{transform:translateY(-7px) rotate(6deg)}}
.dayscene .hv-lamp{animation:hvLamp 2.2s ease-in-out infinite alternate}
@keyframes hvLamp{from{opacity:.7}to{opacity:1}}
.quiet.heiva .qhint{display:none}
.hvsign{flex:none;margin:8px 0}.hvsign svg{width:100%;height:auto;display:block}
.kgauge{position:absolute;right:10px;top:12px;width:14px;height:120px;border-radius:7px;background:rgba(255,255,255,.55);overflow:hidden}
.kgauge i{position:absolute;left:0;right:0;background:rgba(59,140,88,.45)}.kgauge b{position:absolute;left:-2px;right:-2px;height:5px;border-radius:3px;background:#16303B;transition:top .08s linear}
.ktime{position:absolute;left:10px;top:10px;font-family:var(--display);font-weight:800;font-size:.9rem;color:#16303B;background:rgba(255,255,255,.75);border-radius:999px;padding:3px 10px}
.kwind{position:absolute;left:10px;top:40px;font-size:.78rem;font-weight:700;color:#16303B;background:rgba(255,255,255,.65);border-radius:999px;padding:2px 9px}
@media (prefers-reduced-motion:reduce){.dayscene .hv-fl,.dayscene .hv-sp,.dayscene .hv-dance,.dayscene .hv-lamp{animation:none}.dayscene .hv-sp{display:none}}
.pepes{position:absolute;""")
    rep("+paBtn('dol','plDol'):''}","+paBtn('dol','plDol')+'<button class=\"btn\" id=\"plKite\">Le pāuma, le cerf-volant</button>':''}")
    rep("{ const bk=$('#plBall'); if(bk) bk.onclick=()=>openYardGames();","{ const kt=$('#plKite'); if(kt) kt.onclick=()=>openKite(); const bk=$('#plBall'); if(bk) bk.onclick=()=>openYardGames();")
    rep("    else if(v.g==='pardon'){ for(let i=0;i<6;i++)","    else if(v.g==='heiva'){ setTimeout(()=>hvInvite(v),9200); }\n    else if(v.g==='heivaOk'){ hvArrive(v); for(let i=0;i<8;i++) setTimeout(()=>petal(mx+(Math.random()*60-30),my-10),i*180); }\n    else if(v.g==='pardon'){ for(let i=0;i<6;i++)")
    rep("if(m.indexOf('love:')===0){ loveBtn(m.slice(5)); return; }","if(m.indexOf('hv:')===0){ hvBtn(m.split(':')); return; } if(m.indexOf('love:')===0){ loveBtn(m.slice(5)); return; }")
    rep_opt("if(k!=='none' && isNight()) toast('Il fait nuit : le décor reviendra au matin. Les activités restent ouvertes.');","if(k!=='none' && k!=='heiva' && isNight()) toast('Il fait nuit : le décor reviendra au matin. Les activités restent ouvertes.');")
    new = r"""/* ---------- le pāuma : tenir la ligne, ni trop serré ni trop lâche ---------- */
ACT.pauma={t:'Faire voler le pāuma', p:'tino', d:'Tenir la ligne : ni trop serré, ni trop lâche.'};
function kiteDays(){ const a=store.get('kiteDays',[]); return Array.isArray(a)?a:[]; }
const KITE_LV=[{need:0,n:'Brise',dur:45,g:1},{need:3,n:'Alizé',dur:60,g:1.5},{need:7,n:'Rafales',dur:75,g:2.1}];
let KT={};
function openKite(){ const n=kiteDays().length; let lv=0; KITE_LV.forEach((L,i)=>{ if(n>=L.need) lv=i; }); KT={lv, game:null};
  openSheet(`<div class="head"><div><div class="eyebrow">Tahatai · la plage</div><h2>Le pāuma</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div>
    <p>Tout est dans la ligne. Appuie pour la tendre, relâche pour lui laisser du mou. Trop serrée, elle casse ; trop lâche, le pāuma tombe. Le vent change : regarde les cocotiers, il arrive toujours un peu avant.</p>
    <p class="small muted">Niveau : <b>${KITE_LV[lv].n}</b> · ${KITE_LV[lv].dur} secondes à tenir${lv<2?` · le niveau suivant après ${KITE_LV[lv+1].need} jours de pāuma`:''}</p>
    <div class="bkst" id="bkSt" style="height:300px"><canvas id="bkCv" role="img" aria-label="Le pāuma dans le vent"></canvas><div class="bkbird" style="left:4px;bottom:8px;width:56px">${birdSVG(cfg,'kt')}</div><div class="ktime" id="ktTime">${KITE_LV[lv].dur} s</div><div class="kwind" id="ktWind">le vent</div><div class="kgauge" aria-hidden="true"><i style="top:30%;height:35%"></i><b id="ktG" style="top:50%"></b></div></div>
    <p id="ktTxt" class="bktxt" aria-live="polite">Appuie sur la plage pour tendre la ligne. Garde le repère dans la zone verte.</p><button class="btn primary" id="ktGo">Lancer le pāuma</button><button class="btn ghost" id="ktStop">Arrêter</button>`);
  sheetInner.scrollTop=0; const G=bkMount(); if(!G) return; const fx=bkFx(G.st,G.cv); KT.game=kiteGame(G,fx); KT.game.preview();
  const quit=()=>{ if(KT.game) KT.game.stop(); KT.game=null; closeSheet(); }; $('#sx').onclick=quit; $('#ktStop').onclick=quit;
  $('#ktGo').onclick=()=>{ $('#ktGo').hidden=true; $('#ktTxt').textContent='Appuie pour tendre, relâche pour donner du mou.'; KT.game.start(); }; }
function kiteGame(G,fx){ const {cv,ctx,W,H}=G, L=KITE_LV[KT.lv], ax=58, ay=H-42; let s=null, P=[]; const loop=bkLoop(update);
  function reset(){ s={t:0, w:.5, wv:.5, gust:0, gustT:3+Math.random()*3, gustK:0, tau:.5, taus:.5, pull:false, hi:0, lo:0, over:false, ok:false, p1:Math.random()*6, p2:Math.random()*6, sway:0, wob:0}; }
  function wind(){ const base=.45+.22*Math.sin(s.t*.35+s.p1)+.15*Math.sin(s.t*.9+s.p2); return Math.max(.1,Math.min(1,base+s.gust)); }
  function endRun(ok,msg){ if(s.over) return; s.over=true; s.ok=ok; const tx=$('#ktTxt'); if(tx) tx.textContent=msg; const go=$('#ktGo'); if(go){ go.hidden=false; go.textContent=ok?'Terminer':'Relancer'; go.onclick=ok?finish:()=>{ go.hidden=true; if(tx) tx.textContent='Appuie pour tendre, relâche pour donner du mou.'; reset(); P=[]; fx.clear(); }; } }
  function finish(){ try{ const k=dayKey(Date.now()), d=kiteDays(); if(!d.includes(k)){ d.push(k); store.set('kiteDays',d.slice(-60)); const nx=KITE_LV.findIndex(x=>x.need===d.length); if(nx>0) setTimeout(()=>toast('Nouveau niveau de pāuma : '+KITE_LV[nx].n),1400); } }catch(e){} loop.stop(); KT.game=null; placeDone('pauma','Ni trop serré, ni trop lâche. Ça marche aussi avec ce quʼon tient dans sa tête.'); }
  bkPointer(cv,{ down(){ if(s && !s.over) s.pull=true; }, up(){ if(s) s.pull=false; } });
  function update(dt,t){ if(!s) return; if(!s.over){ s.t+=dt;
      s.gustT-=dt; if(s.gustT<=0 && !s.gustK){ s.gustK=1; s.gustT=(4+Math.random()*4)/L.g; } if(s.gustK){ const ph=s.gustK; s.gustK+=dt; const d=3.2; const k=ph<1?ph:ph<2.2?1:Math.max(0,1-(ph-2.2)); s.gust=k*(.32+.12*L.g); if(ph>d){ s.gustK=0; s.gust=0; } } else s.gust*=Math.pow(.1,dt);
      s.w=wind(); s.wv+=(s.w-s.wv)*Math.min(1,dt*2.5);
      const dr=((s.pull?.9:-.55)+(s.w-.5)*1.1)*.36*(1+(L.g-1)*.25); s.tau=Math.max(0,Math.min(1,s.tau+dr*dt)); s.taus+=(s.tau-s.taus)*Math.min(1,dt*6);
      if(s.tau>=.97){ s.hi+=dt; if(s.hi>.45){ fx.shake(3,140); bkBurst(P,kx(),ky(),10,['#fff','#F2C94C']); endRun(false,'La ligne a cassé : trop serrée, trop longtemps. On relâche un peu, et on relance.'); } } else s.hi=Math.max(0,s.hi-dt*2);
      if(s.tau<=.06){ s.lo+=dt; if(s.lo>.8) endRun(false,'Le pāuma est tombé : trop de mou. Un peu de tension, et il remonte.'); } else s.lo=Math.max(0,s.lo-dt*2);
      if(s.t>=L.dur && !s.over){ fx.flash(); bkBurst(P,kx(),ky(),18,['#F2C94C','#E4583F','#fff']); endRun(true,'Il est resté en lʼair tout ce temps. Ni trop serré, ni trop lâche : tu as tenu la ligne.'); }
      const tm=$('#ktTime'); if(tm) tm.textContent=Math.max(0,Math.ceil(L.dur-s.t))+' s'; const g=$('#ktG'); if(g) g.style.top=(100-s.tau*100)+'%'; const wn=$('#ktWind'); if(wn){ const nm = (typeof SKYW!=='undefined') ? (s.w>.72?'Maraʻamu · fort':s.w>.4?'Maoaʻe · régulier':'brise légère') : (s.w>.72?'vent fort':s.w>.4?'vent régulier':'brise légère'); wn.textContent=nm; } }
    s.sway+=(s.wv-s.sway)*Math.min(1,dt*3); s.wob+=dt; draw(t,dt); }
  const ang=()=>(14+56*s.taus)*Math.PI/180, len=()=>150+30*s.wv;
  function kx(){ return ax+Math.cos(ang())*len()+Math.sin(s.wob*5)*4*s.wv; } function ky(){ return ay-Math.sin(ang())*len()+Math.cos(s.wob*3.7)*3*s.wv + (s.over&&!s.ok ? Math.min(220,(s.t)*0) : 0); }
  function palm(x,y,sc,flip){ ctx.save(); ctx.translate(x,y); ctx.scale(flip?-sc:sc,sc); ctx.strokeStyle='#9A7748'; ctx.lineWidth=7; ctx.lineCap='round'; ctx.beginPath(); ctx.moveTo(0,0); ctx.quadraticCurveTo(-8,-60,18,-110); ctx.stroke(); ctx.save(); ctx.translate(18,-110); ctx.rotate(s.sway*.25-.1); ctx.fillStyle='#2F8A50'; for(const a of [-2.6,-2.1,-1.5,-.9,-.3,.2]){ ctx.save(); ctx.rotate(a+Math.sin(s.wob*4+a)*.06*s.wv); ctx.beginPath(); ctx.moveTo(0,0); ctx.quadraticCurveTo(26,-18,56,4); ctx.quadraticCurveTo(28,-4,0,0); ctx.fill(); ctx.restore(); } ctx.restore(); ctx.restore(); }
  function draw(t,dt){ const gr=ctx.createLinearGradient(0,0,0,H); gr.addColorStop(0,'#8CC6EE'); gr.addColorStop(.6,'#DDF1FA'); ctx.fillStyle=gr; ctx.fillRect(0,0,W,H); ctx.fillStyle='#4DB6C9'; ctx.fillRect(0,H*.62,W,H*.14); ctx.fillStyle='rgba(255,255,255,.5)'; for(let i=0;i<4;i++){ ctx.beginPath(); ctx.ellipse((i*97+s.wob*20)%(W+60)-30,H*.66+i*7,24,2.2,0,0,Math.PI*2); ctx.fill(); } ctx.fillStyle='#F1DDB0'; ctx.fillRect(0,H*.76,W,H*.24);
    palm(W-40,H*.78,.9,true); palm(W-96,H*.79,.6,false); ctx.fillStyle='#8A5A2B'; ctx.fillRect(W*.45,H*.8,4,26); ctx.save(); ctx.translate(W*.45+2,H*.8); ctx.rotate(-.05); ctx.fillStyle='#E9D3A0'; ctx.strokeStyle='#5C3A1E'; ctx.lineWidth=1.4; ctx.fillRect(-46,-24,92,24); ctx.strokeRect(-46,-24,92,24); ctx.fillStyle='#3A2412'; ctx.font='800 8px sans-serif'; ctx.textAlign='center'; ctx.fillText('Pāuma : jamais près',0,-14); ctx.fillText('des fils électriques',0,-5); ctx.restore();
    const x=kx(), y=ky(); const sag=(1-s.taus)*46; ctx.strokeStyle= s.tau>=.9?'#C8402F':'rgba(22,48,59,.75)'; ctx.lineWidth=1.4; ctx.beginPath(); ctx.moveTo(ax,ay); ctx.quadraticCurveTo((ax+x)/2,(ay+y)/2+sag,x,y); ctx.stroke();
    ctx.save(); ctx.translate(x,y); ctx.rotate(-ang()+Math.PI/2+Math.sin(s.wob*6)*.08*s.wv); ctx.fillStyle='#E4583F'; ctx.beginPath(); ctx.moveTo(0,-26); ctx.lineTo(18,0); ctx.lineTo(0,34); ctx.lineTo(-18,0); ctx.closePath(); ctx.fill(); ctx.fillStyle='#F2C94C'; ctx.beginPath(); ctx.moveTo(0,-26); ctx.lineTo(18,0); ctx.lineTo(0,0); ctx.closePath(); ctx.fill(); ctx.beginPath(); ctx.moveTo(0,34); ctx.lineTo(-18,0); ctx.lineTo(0,0); ctx.closePath(); ctx.fill(); ctx.strokeStyle='#8E1322'; ctx.lineWidth=1.2; ctx.beginPath(); ctx.moveTo(0,-26); ctx.lineTo(0,34); ctx.moveTo(-18,0); ctx.lineTo(18,0); ctx.stroke();
    ctx.strokeStyle='#16303B'; ctx.lineWidth=1; ctx.beginPath(); ctx.moveTo(0,34); for(let i=1;i<=5;i++){ ctx.lineTo(Math.sin(s.wob*7+i)*8*(.4+s.wv), 34+i*12); } ctx.stroke(); for(let i=1;i<=3;i++){ const bx=Math.sin(s.wob*7+i*1.6)*8*(.4+s.wv), by=34+i*19; ctx.fillStyle=i%2?'#F2C94C':'#2BB3C0'; ctx.beginPath(); ctx.moveTo(bx-6,by-4); ctx.lineTo(bx+6,by+4); ctx.lineTo(bx+6,by-4); ctx.lineTo(bx-6,by+4); ctx.closePath(); ctx.fill(); } ctx.restore();
    bkParts(ctx,P,dt); }
  return { start(){ reset(); loop.start(); }, stop(){ loop.stop(); fx.clear(); }, preview(){ reset(); draw(0,0); }, get s(){ return s; }, setPull(v){ if(s) s.pull=!!v; } }; }

/* ---------- Te Heiva : le feu, la danse, le bar à jus, les cœurs liés autour du feu ---------- */
const HEIVA_PLACE={n:'Te Heiva', s:'la fête, le soir', a:'Le Heiva', d:'Un feu sur la plage, la musique, les amis. On danse, on boit un jus, on rit.'};
GEST.heiva={l:'', t:'tʼinvite au Heiva, autour du feu.'}; GEST.heivaOk={l:'', t:'arrive au Heiva et danse autour de ton feu !'};
function hvGet(){ const o=store.get('heiva',null); return (o && typeof o==='object') ? Object.assign({lit:'', circle:{}, guestDay:'', seen:false, juice:''},o) : {lit:'', circle:{}, guestDay:'', seen:false, juice:''}; }
function hvSongsOk(){ try{ return TUNES.filter(t=>!t.duo).every(t=>t.ok()); }catch(e){ return false; } }
function hvOpen(){ const h=hvGet(); return hvSongsOk() || h.guestDay===dayKey(Date.now()); }
function hvSync(){ const was=!!PLACES.heiva; if(hvOpen()) PLACES.heiva=HEIVA_PLACE; else { delete PLACES.heiva; if(curPlace==='heiva') setPlace('none'); } if(!was && PLACES.heiva){ const h=hvGet(); if(!h.seen && hvSongsOk()){ h.seen=true; store.set('heiva',h); setTimeout(function w(){ if(!visitFree() || bubbleEl.classList.contains('show') || !$('#sheet').hidden){ setTimeout(w,6000); return; } say('Tu connais tous mes airs… Alors ce soir, cʼest le Heiva ! Un nouveau lieu sʼest ouvert : le feu sur la plage.'); },1500); } try{ dockRender(); }catch(e){} } }
function hvGuests(){ const h=hvGet(), k=dayKey(Date.now()); return friends.filter(f=>h.circle[f.code]===k).slice(0,4).map(f=>{ const d=FR[f.code]; let look={}; try{ look=cleanCfg(d&&d!=='err'&&d.cfg?d.cfg:{}); }catch(e){} return {code:f.code, name:(f.name||fmtCode(f.code)).slice(0,12), look}; }); }
function hvScene(){ const h=hvGet(), lit=h.lit===dayKey(Date.now()); let st=''; let seed=7; const rnd=()=>{ seed=(seed*16807)%2147483647; return seed/2147483647; }; for(let i=0;i<70;i++) st+=`<circle cx="${(rnd()*360).toFixed(0)}" cy="${(rnd()*300).toFixed(0)}" r="${(.5+rnd()*.9).toFixed(1)}" fill="#fff" opacity="${(.3+rnd()*.5).toFixed(2)}"/>`;
  const guests=hvGuests(); const pos=[[96,578],[262,578],[62,540],[296,540]];
  const gsvg=guests.map((g,i)=>{ const p=pos[i]; const b=birdSVG(g.look,'hv'+i).replace('<svg ',`<svg x="${p[0]-30}" y="${p[1]-58}" width="60" height="55" `); return `<g class="hv-dance" style="animation-delay:-${(i*.17).toFixed(2)}s">${b}</g><text x="${p[0]}" y="${p[1]+8}" text-anchor="middle" font-size="8.5" font-weight="700" fill="#FFE2A8" font-family="sans-serif">${esc(g.name)}</text>`; }).join('');
  const fire = lit ? `<g><path class="hv-fl" d="M180 560 q-26 -22 -18 -50 q6 14 14 16 q-4 -24 14 -40 q2 26 18 36 q10 -10 8 -26 q16 24 2 54 q-14 16 -38 10z" fill="#F08A2B"/><path class="hv-fl hv-fl2" d="M180 556 q-14 -14 -10 -32 q4 10 10 12 q-2 -16 10 -26 q2 18 12 24 q6 -6 6 -16 q10 16 0 34 q-10 10 -28 4z" fill="#F2C94C"/><path class="hv-fl hv-fl2" d="M181 552 q-6 -8 -4 -18 q2 6 6 8 q0 -10 6 -14 q2 10 6 12 q4 8 -2 14 q-6 4 -12 -2z" fill="#FFF3C4"/><g fill="#FFE08A">${[0,1,2,3,4].map(i=>`<circle class="hv-sp" style="animation-delay:-${(i*.34).toFixed(2)}s" cx="${172+i*5}" cy="${520-i*6}" r="${1.6+(i%2)*.8}"/>`).join('')}</g></g>` : `<g fill="#3A2412" opacity=".7"><ellipse cx="174" cy="560" rx="6" ry="2.4"/><ellipse cx="186" cy="562" rx="5" ry="2"/></g>`;
  return `<defs><linearGradient id="scSky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#071426"/><stop offset=".55" stop-color="#12304A"/><stop offset="1" stop-color="#1B4A62"/></linearGradient><radialGradient id="hvGlow" cx="180" cy="556" r="150" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#F2A23A" stop-opacity="${lit?'.55':'0'}"/><stop offset="1" stop-color="#F2A23A" stop-opacity="0"/></radialGradient></defs><rect x="-1400" y="-700" width="3160" height="1340" fill="url(#scSky)"/>${st}
  <circle cx="290" cy="90" r="18" fill="#FFF1C4"/><circle cx="283" cy="84" r="16" fill="#0E2238" opacity=".92"/>
  <g transform="translate(0 -95)"><rect x="-1400" y="380" width="3160" height="90" fill="#0E3A55"/><path d="M-1400 470 H1760 V1340 H-1400Z" fill="#B59A6E"/><path d="M-1400 470 q180 -6 360 0 t360 0 t360 0 V480 H-1400Z" fill="#8FA7B5" opacity=".5"/>
  <path d="M230 392 q24 6 50 0" stroke="#FFF1C4" stroke-width="1.4" opacity=".5" fill="none"/><path d="M236 420 q22 5 44 0" stroke="#FFF1C4" stroke-width="1.2" opacity=".35" fill="none"/>
  <g opacity=".9"><path d="M30 470 q-8 -80 30 -150 l6 3 q-32 70 -26 147z" fill="#0B1E2E"/><g fill="#0B1E2E">${[-150,-115,-75,-35,5,25].map(a=>`<path d="M0 0 Q28 -22 62 4 Q30 -6 0 0Z" transform="translate(66 320) rotate(${a})"/>`).join('')}</g><path d="M330 470 q8 -70 -24 -130 l-6 3 q28 60 20 127z" fill="#0B1E2E"/><g fill="#0B1E2E">${[-30,-65,-105,-145,-175,-200].map(a=>`<path d="M0 0 Q28 -22 62 4 Q30 -6 0 0Z" transform="translate(300 340) rotate(${a})"/>`).join('')}</g></g>
  <path d="M40 300 Q180 330 320 300" stroke="#5C4A2E" stroke-width="1.2" fill="none"/><g>${[0,1,2,3,4,5,6].map(i=>`<circle class="hv-lamp" style="animation-delay:-${(i*.3).toFixed(1)}s" cx="${60+i*40}" cy="${306+Math.sin(i/6*Math.PI)*22}" r="4" fill="${i%2?'#FFE08A':'#F2A23A'}"/>`).join('')}</g>
  <rect x="-1400" y="380" width="3160" height="500" fill="url(#hvGlow)"/>
  <g transform="translate(284 548)"><rect x="-22" y="-14" width="44" height="26" rx="6" fill="#8A5A2B" stroke="#5C3A1E" stroke-width="1.4"/><path d="M-22 -4 h44" stroke="#5C3A1E" stroke-width="1"/><rect x="-18" y="12" width="5" height="10" fill="#5C3A1E"/><rect x="13" y="12" width="5" height="10" fill="#5C3A1E"/><path d="M-6 -22 l8 8 M8 -24 l-6 10" stroke="#F1DDB0" stroke-width="2" stroke-linecap="round"/></g>
  <g transform="translate(66 538)"><rect x="-3" y="0" width="6" height="40" fill="#8A5A2B"/><rect x="-30" y="-28" width="60" height="30" rx="3" fill="#C99A5B" stroke="#5C3A1E" stroke-width="1.4"/><text x="0" y="-16" text-anchor="middle" font-size="8.5" font-weight="800" fill="#3A2412" font-family="sans-serif">BAR DU HEIVA</text><g transform="translate(-18 -10)"><path d="M0 0 h7 l-1 8 h-5z" fill="#F2C94C"/><path d="M12 0 h7 l-1 8 h-5z" fill="#F7A8C4"/><path d="M24 0 h7 l-1 8 h-5z" fill="#FFF3D6"/><path d="M36 -2 l3 -4 M36 -2 h7 l-1 10 h-5z" fill="#BFE6D8" stroke="#3A2412" stroke-width=".5"/></g></g>
  <g transform="translate(314 596) rotate(-7)"><rect x="-3" y="0" width="6" height="34" fill="#8A5A2B"/><rect x="-36" y="-30" width="72" height="32" rx="3" fill="#E9D3A0" stroke="#5C3A1E" stroke-width="1.4"/><text x="-4" y="-18" text-anchor="middle" font-size="6.2" font-weight="800" fill="#3A2412" font-family="sans-serif">Ici, les seuls qui planent,</text><text x="-4" y="-9" text-anchor="middle" font-size="6.2" font-weight="800" fill="#3A2412" font-family="sans-serif">ce sont les manu.</text><g transform="translate(22 -24) scale(.42)"><circle cx="8" cy="22" r="7" fill="#8A5A2B"/><path d="M4 16 l-3 -6 M8 15 v-7 M12 16 l3 -6" stroke="#3B8C58" stroke-width="2" stroke-linecap="round"/></g></g>
  ${gsvg}
  <g transform="translate(180 560)"><path d="M-26 6 l16 -10 M26 6 l-16 -10 M-20 -2 l40 8" stroke="#6B4A2A" stroke-width="5" stroke-linecap="round"/></g>
  <g fill="#8A8F94" stroke="#5C6B73" stroke-width=".8">${[[-36,4],[-26,-6],[-12,-10],[4,-11],[20,-8],[33,0],[30,9],[14,13],[-4,14],[-22,12]].map(q=>`<ellipse cx="${180+q[0]}" cy="${562+q[1]*.6}" rx="6" ry="4"/>`).join('')}</g>
  <g transform="translate(232 556)"><path d="M-9 -14 h18 l-3 18 h-12z" fill="#7FB2C9" stroke="#3B6F86" stroke-width="1.2"/><path d="M-9 -14 q9 -10 18 0" fill="none" stroke="#3B6F86" stroke-width="1.2"/><ellipse cx="0" cy="-13" rx="8" ry="2" fill="#BFE6F5"/></g>
  ${lit?`<g transform="translate(134 572)"><circle cx="0" cy="-56" r="9" fill="#8A5A2B"/><path d="M-8 -60 q8 -8 16 0" fill="#22323A"/><path d="M-12 -46 h24 l4 40 h-32z" fill="#3B8C58"/><path d="M-12 -40 l-6 18 M12 -40 l8 14" stroke="#8A5A2B" stroke-width="4" stroke-linecap="round"/><text x="0" y="10" text-anchor="middle" font-size="8.5" font-weight="700" fill="#FFE2A8" font-family="sans-serif">tonton</text></g>`:''}
  ${fire}
  <ellipse cx="180" cy="566" rx="34" ry="5" fill="#3A2412" opacity=".35"/></g>`; }
function hvSignSVG(which){ if(which==='bar') return `<svg viewBox="0 0 320 150" role="img" aria-label="Bar du Heiva : jus dʼananas, jus de pamplemousse, eau de coco, lait de coco au miel. Cʼest tout, et cʼest déjà beaucoup."><rect x="150" y="118" width="20" height="32" fill="#8A5A2B"/><rect x="10" y="8" width="300" height="112" rx="10" fill="#C99A5B" stroke="#5C3A1E" stroke-width="3"/><path d="M26 22 h268 M26 106 h268" stroke="#5C3A1E" stroke-width="1" opacity=".5"/><text x="160" y="40" text-anchor="middle" font-size="19" font-weight="900" fill="#3A2412" font-family="sans-serif">BAR DU HEIVA</text><text x="160" y="62" text-anchor="middle" font-size="12.5" font-weight="700" fill="#3A2412" font-family="sans-serif">jus dʼananas · jus de pamplemousse</text><text x="160" y="79" text-anchor="middle" font-size="12.5" font-weight="700" fill="#3A2412" font-family="sans-serif">eau de coco · lait de coco au miel</text><text x="160" y="98" text-anchor="middle" font-size="11" font-style="italic" fill="#5C3A1E" font-family="sans-serif">Cʼest tout, et cʼest déjà beaucoup.</text><g transform="translate(26 30)"><path d="M0 0 h12 l-2 16 h-8z" fill="#F2C94C" stroke="#3A2412" stroke-width="1"/><path d="M20 0 h12 l-2 16 h-8z" fill="#F7A8C4" stroke="#3A2412" stroke-width="1"/></g><g transform="translate(262 30)"><path d="M0 0 h12 l-2 16 h-8z" fill="#FFF3D6" stroke="#3A2412" stroke-width="1"/><path d="M20 0 h12 l-2 16 h-8z" fill="#BFE6D8" stroke="#3A2412" stroke-width="1"/><path d="M26 0 l4 -6" stroke="#3A2412" stroke-width="1.2"/></g></svg>`;
  return `<svg viewBox="0 0 320 130" role="img" aria-label="Pancarte : Ici, les seuls qui planent, ce sont les manu."><g transform="translate(160 65) rotate(-4)"><rect x="-8" y="40" width="16" height="30" fill="#8A5A2B"/><rect x="-150" y="-52" width="300" height="94" rx="8" fill="#E9D3A0" stroke="#5C3A1E" stroke-width="3"/><text x="-18" y="-16" text-anchor="middle" font-size="16" font-weight="900" fill="#3A2412" font-family="sans-serif">Ici, les seuls qui planent,</text><text x="-18" y="8" text-anchor="middle" font-size="16" font-weight="900" fill="#3A2412" font-family="sans-serif">ce sont les manu.</text><g transform="translate(96 -34) scale(.55)">${birdSVG(cfg,'hvs').replace('<svg ','<svg width="120" height="110" ')}</g><g transform="translate(118 26)"><circle cx="0" cy="0" r="9" fill="#8A5A2B" stroke="#5C3A1E" stroke-width="1"/><path d="M-5 -8 l-3 -6 M0 -9 v-8 M5 -8 l3 -6" stroke="#3B8C58" stroke-width="2.4" stroke-linecap="round"/><path d="M2 -3 l5 -9" stroke="#fff" stroke-width="2" stroke-linecap="round"/></g></g></svg>`; }
function hvHead(t){ return `<div class="head"><div><div class="eyebrow">Te Heiva · la fête, le soir</div><h2>${t}</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div>`; }
function hvReward(){ try{ const k=dayKey(Date.now()); if(store.get('hvDay','')!==k){ store.set('hvDay',k); feathers+=1; store.set('feathers',feathers); renderFeathers(); } }catch(e){} }
function hvRefresh(){ try{ const el=$('#dayScene'); if(el) el.dataset.p=''; renderPlace(); }catch(e){} }
function openHeiva(){ const h=hvGet(), k=dayKey(Date.now()), lit=h.lit===k, guests=hvGuests(), mut=(SYNC_URL?friends.filter(f=>isMutual(f.code)):[]);
  if(!lit && h.lit && h.out!==h.lit){ openSheet(hvHead('Le feu dʼhier')+`<p>Avant tout, on vérifie le feu de la dernière fois. Même sʼil a lʼair mort, des braises peuvent rester chaudes sous la cendre.</p><div class="card flat"><p class="small">Un seau dʼeau de mer dessus, puis du sable par-dessus, et on touche du dos de la main au-dessus : plus aucune chaleur.</p></div><button class="btn primary" id="hvOut">Verser lʼeau et couvrir de sable</button>`); $('#sx').onclick=closeSheet; $('#hvOut').onclick=()=>{ const h2=hvGet(); h2.out=h2.lit; store.set('heiva',h2); closeSheet(); hvRefresh(); say('Pschhh… Plus une braise. Un feu bien éteint, cʼest la fin dʼune belle soirée.'); }; return; }
  if(!lit){ openSheet(hvHead('Le Heiva')+`<p>La nuit est tombée sur la plage. Les tōʻere sont là, les lanternes aussi. Il ne manque que le feu. Un feu, cʼest un adulte qui lʼallume : on va chercher tonton.</p><div class="hvsign">${hvSignSVG('bar')}</div><button class="btn primary" id="hvLit">Demander à tonton dʼallumer le feu</button>`); $('#sx').onclick=closeSheet;
    $('#hvLit').onclick=()=>{ const h2=hvGet(); h2.lit=k; const first=!h2.safe; h2.safe=1; store.set('heiva',h2); hvReward(); closeSheet(); hvRefresh(); say(first?'Tonton : « Un feu, on le fait avec un adulte, sur le sable, loin des arbres, et on lʼéteint avec de lʼeau avant de partir. » Et voilà, il brûle !':'Tonton allume le feu. Ce soir, on danse. Et on boit du jus de fruit, comme tous les manu.'); setTimeout(()=>{ if(visitFree()) say('Invite tes cœurs liés : plus on est de manu autour du feu, plus la nuit est belle.'); },7000); }; return; }
  openSheet(hvHead('Autour du feu')+`<p>${guests.length?`Ce soir, autour du feu : <b>${guests.map(g=>esc(g.name)).join(', ')}</b> et toi.`:'Pour lʼinstant, il nʼy a que toi et ton manu. Ça suffit pour danser, mais on peut inviter du monde.'}</p>
    <div class="bkpick"><button class="btn primary" id="hvDance"><b>Danser</b><br><span class="small">Choisis un air : ton manu joue, les invités dansent.</span></button>
    ${mut.length?`<button class="btn" id="hvInv"><b>Inviter des cœurs liés</b><br><span class="small muted">Leur manu viendra danser autour de ton feu.</span></button>`:''}
    <button class="btn" id="hvBar"><b>Le bar</b><br><span class="small muted">Jus dʼananas, pamplemousse, coco…</span></button><button class="btn ghost" id="hvEnd"><b>Fin de soirée : éteindre le feu</b><br><span class="small muted">Avec tonton, un seau dʼeau de mer et du sable.</span></button></div>
    <div class="hvsign">${hvSignSVG('planent')}</div>`);
  $('#sx').onclick=closeSheet;
  $('#hvDance').onclick=()=>{ const ok=TUNES.filter(t=>t.ok()&&!t.duo); openSheet(hvHead('Danser')+`<div class="stack">${ok.map(t=>`<button class="pans" data-t="${t.id}"><b>${t.n}</b><span class="small">${esc(t.s||'')}</span></button>`).join('')}</div>`); $('#sx').onclick=closeSheet; sheetInner.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{ closeSheet(); hvDance(b.dataset.t); }); };
  const inv=$('#hvInv'); if(inv) inv.onclick=()=>{ openSheet(hvHead('Inviter au Heiva')+`<p class="small muted">Chacun reçoit lʼinvitation à sa prochaine ouverture de Manu Ora. Sʼil accepte, son manu apparaît autour de ton feu ce soir, et le tien autour du sien.</p><div class="row" id="hvFr">${mut.map(f=>`<button class="btn sm" data-f="${f.code}">${esc(f.name||fmtCode(f.code))}</button>`).join('')}</div>`); $('#sx').onclick=closeSheet;
    $('#hvFr').addEventListener('click', e=>{ const b=e.target.closest('[data-f]'); if(!b) return; const code=b.dataset.f, f=friends.find(x=>x.code===code), nm=f?(f.name||fmtCode(code)):''; sendGesture(code,'heiva',nm); b.disabled=true; b.textContent='Invité·e'; toast('Invitation envoyée à '+nm); }); };
  $('#hvEnd').onclick=()=>{ const h2=hvGet(); h2.out=h2.lit; h2.lit=''; store.set('heiva',h2); closeSheet(); hvRefresh(); say('Pschhh… Le seau dʼeau, puis le sable. Plus une braise : on peut rentrer tranquilles.'); };
  $('#hvBar').onclick=()=>{ openSheet(hvHead('Le bar')+`<div class="hvsign">${hvSignSVG('bar')}</div><div class="opt" id="hvJ">${[['ana','Jus dʼananas'],['pam','Jus de pamplemousse'],['coco','Eau de coco'],['meli','Lait de coco au miel']].map(x=>`<button data-j="${x[0]}">${x[1]}</button>`).join('')}</div>`); $('#sx').onclick=closeSheet;
    $('#hvJ').addEventListener('click', e=>{ const b=e.target.closest('[data-j]'); if(!b) return; const j=b.dataset.j; const h2=hvGet(); h2.juice=k; store.set('heiva',h2); closeSheet(); say({ana:'Un jus dʼananas bien frais. Santé ! À la tienne.',pam:'Jus de pamplemousse, le vrai, celui de Moʻorea. Santé !',coco:'Lʼeau dʼun coco qui vient de tomber. Rien de meilleur.',meli:'Lait de coco au miel : doux comme la soirée. Santé !'}[j]); for(let i=0;i<6;i++) setTimeout(()=>petal(B.x+BW/2+(Math.random()*60-30),B.y+10),i*180); }); }; }
function hvDance(id){ try{ playUke(id,{after:()=>{ hvReward(); say('ʻOaʻoa ! Tu as vu les invités danser ? Encore un air ?'); }}); }catch(e){} }
function hvInvite(v){ if(!visitFree() || bubbleEl.classList.contains('show')){ setTimeout(()=>hvInvite(v),5000); return; } sayHTML(`${esc(v.name)} tʼinvite au Heiva : un feu sur la plage, de la musique, des amis. On y va ?<div class="mini"><button data-m="hv:go:${v.from}">Jʼy vais</button><button data-m="hv:no">Plus tard</button></div>`, 40000); }
function hvArrive(v){ try{ const h=hvGet(), k=dayKey(Date.now()); h.circle[v.from]=k; store.set('heiva',h); hvSync(); hvRefresh(); setTimeout(()=>{ if(visitFree()) say(esc(v.name)+' est arrivé·e au Heiva ! Son manu danse autour du feu.'); },9400); }catch(e){} }
function hvBtn(a){ bubbleEl.classList.remove('show'); if(a[1]==='go'){ const f=friends.find(x=>x.code===a[2]); if(!f) return; const h=hvGet(), k=dayKey(Date.now()); h.circle[f.code]=k; h.guestDay=k; if(h.lit!==k) h.lit=k; store.set('heiva',h); sendGesture(f.code,'heivaOk',f.name||fmtCode(f.code)); hvSync(); if(cfg.night==='on'){ cfg.night='auto'; store.set('cfg',cfg); renderNight(); } if(!QUIET) setQuiet(true); setPlace('heiva'); hvRefresh(); say('On y va ! Le manu de '+(f.name||fmtCode(f.code))+' nous attend près du feu.'); } }
{ const _si=sceneInner; sceneInner=function(id){ return id==='heiva' ? hvScene() : _si.apply(this,arguments); };
  const _rp=renderPlace; renderPlace=function(){ const r=_rp.apply(this,arguments); try{ const q=$('#quiet'), el=$('#dayScene'), ns=$('#nightSky'); if(q) q.classList.toggle('heiva', curPlace==='heiva' && !!PLACES.heiva); if(q && el && curPlace==='heiva' && PLACES.heiva){ if(el.dataset.p!=='heiva'){ el.innerHTML=hvScene(); el.dataset.p='heiva'; } el.removeAttribute('hidden'); q.classList.add('scene','night'); if(ns) ns.setAttribute('hidden',''); try{ document.documentElement.setAttribute('data-theme','dark'); }catch(e){} } }catch(e){} return r; };
  const _rn=renderNight; renderNight=function(){ const r=_rn.apply(this,arguments); try{ if(curPlace==='heiva' && PLACES.heiva) renderPlace(); }catch(e){} return r; };
  const _pa=placeAct; placeAct=function(){ if(curPlace==='heiva'){ openHeiva(); return; } return _pa.apply(this,arguments); };
  const _cs=closeSheet; closeSheet=function(){ const r=_cs.apply(this,arguments); setTimeout(hvSync,800); return r; }; }
setTimeout(()=>{ try{ hvSync(); if(typeof QI!=='undefined'){ QI.heiva='<rect x="2" y="2" width="24" height="24" rx="7" fill="#12304A"/><path d="M14 23 q-7 -6 -4 -13 q1 4 4 5 q-1 -7 4 -11 q1 7 5 10 q3 -3 2 -7 q5 7 0 14 q-4 4 -11 2z" fill="#F08A2B"/><path d="M14 22 q-3 -4 -1 -8 q1 3 3 3 q0 -4 3 -6 q1 5 3 6 q2 3 -1 6 q-3 2 -7 -1z" fill="#F2C94C"/>'; QI.pauma='<path d="M14 2 L24 11 L14 24 L4 11Z" fill="#E4583F"/><path d="M14 2 L24 11 L14 11Z M14 24 L4 11 L14 11Z" fill="#F2C94C"/><path d="M14 2 V24 M4 11 H24" stroke="#8E1322" stroke-width="1"/><path d="M14 24 q-4 2 -3 4" stroke="#16303B" stroke-width="1.2" fill="none"/>'; QI.danse='<circle cx="9" cy="20" r="4" fill="#F2C94C"/><circle cx="19" cy="18" r="4" fill="#F2C94C"/><path d="M13 20 V6 l10 -2 V18" stroke="#16303B" stroke-width="2.2" fill="none" stroke-linejoin="round"/>'; QI.bar='<path d="M8 6 h12 l-2 16 h-8z" fill="#F7A8C4" stroke="#16303B" stroke-width="1.2"/><path d="M8 11 h12" stroke="#16303B" stroke-width="1"/><path d="M16 6 l4 -4" stroke="#16303B" stroke-width="1.4"/><circle cx="21" cy="3" r="1.6" fill="#E4583F"/>'; QI.inviter='<circle cx="10" cy="10" r="4" fill="#2F80D8"/><circle cx="19" cy="11" r="3.4" fill="#E4583F"/><path d="M3 22 q7 -8 14 0 M15 22 q4 -6 9 -2" stroke="#16303B" stroke-width="1.8" fill="none"/>'; QPL.heiva='Heiva';
      const _qa3=qActs; qActs=function(){ const a=_qa3.apply(this,arguments); if(curPlace==='tai') a.push({k:'pauma',l:'Pāuma',t:'Le pāuma, le cerf-volant',go:openKite}); if(curPlace==='heiva'){ const h=hvGet(), lit=h.lit===dayKey(Date.now()); return [{k:'heiva',l:'Le feu',t:'Le Heiva',go:openHeiva}].concat(lit?[{k:'danse',l:'Danser',t:'Danser',go:()=>{ openHeiva(); const b=$('#hvDance'); if(b) b.click(); }},{k:'bar',l:'Le bar',t:'Le bar à jus',go:()=>{ openHeiva(); const b=$('#hvBar'); if(b) b.click(); }}].concat(SYNC_URL&&friends.some(f=>isMutual(f.code))?[{k:'inviter',l:'Inviter',t:'Inviter des cœurs liés',go:()=>{ openHeiva(); const b=$('#hvInv'); if(b) b.click(); }}]:[]):[]); } return a; }; dockRender(); } }catch(e){} },200);
setInterval(hvSync,60000);

"""
    rep("/* ---------- install button ---------- */", new+"/* ---------- install button ---------- */")
    open(path,'w',encoding='utf8').write(s)
    print('ok',path)
