// node test_vivo.js [fichier] — vivo caché, ʻofe à la rivière, seconde chance, ʻūʻupa offert à une amie.
const {chromium}=require('playwright');const FILE=process.argv[2]||'/tmp/claude-0/v91j.html',O='/home/claude/work/';
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--headless=new']});
const db={};const mk=async(code,name)=>{const ctx=await b.newContext({viewport:{width:390,height:800},timezoneId:'Pacific/Tahiti'});const p=await ctx.newPage();p.errs=[];p.on('pageerror',e=>p.errs.push(e.message));
 await p.exposeFunction('dbOp',(method,path,body)=>{const ks=path.split('/').filter(Boolean);let o=db;if(method==='GET'){for(const k of ks){o=o&&o[k];}return o===undefined?null:JSON.parse(JSON.stringify(o));}const last=ks.pop();for(const k of ks){o[k]=o[k]||{};o=o[k];}const v=body?JSON.parse(body):null;if(method==='PUT')o[last]=v;else if(method==='PATCH'){o[last]=o[last]||{};for(const k in v){if(v[k]===null)delete o[last][k];else o[last][k]=v[k];}}else if(method==='DELETE')delete o[last];return {};});
 await p.addInitScript(([code,name])=>{localStorage.setItem('manuora.welcomed','true');localStorage.setItem('manuora.v','3');localStorage.setItem('manuora.code',JSON.stringify(code));localStorage.setItem('manuora.share',JSON.stringify({on:true,name}));localStorage.setItem('manuora.place',JSON.stringify('vai'));window.fetch=async(u,o)=>{o=o||{};const path=String(u).replace(/^https?:\/\/[^/]+\//,'').replace(/\.json$/,'');const r=await window.dbOp(o.method||'GET',path,o.body||null);return {ok:true,json:async()=>r};};},[code,name]);
 await p.goto('file://'+FILE);await p.waitForTimeout(1200);await p.evaluate(()=>closeSheet());return p;};
const A=await mk('AAAA2222','Teva'),B=await mk('BBBB3333','Hina');
await A.evaluate(()=>{friends.push({code:'BBBB3333',name:'Hina'});store.set('friends',friends)});await B.evaluate(()=>{friends.push({code:'AAAA2222',name:'Teva'});store.set('friends',friends)});
for(const P of [A,B]) await P.evaluate(()=>pushHeart());await A.waitForTimeout(300);for(const P of [A,B]) await P.evaluate(()=>fetchFriends());
const clear=P=>P.evaluate(()=>{try{if(RING.open)closeRing()}catch(e){};if(!$('#sheet').hidden)closeSheet();bubbleEl.classList.remove('show');});await clear(A);
await A.evaluate(()=>openInstr());console.log('caché au départ',await A.evaluate(()=>!/vivo|\?\?\?\?/.test(sheetInner.textContent)));
await A.evaluate(()=>{store.set('instr',{uke:{fin:'nat',day:''},toere:{fin:'nat',day:''},pahu:{fin:'nat',day:''}});openInstr();});console.log('indice',await A.evaluate(()=>/là où lʼeau chante/.test(sheetInner.textContent)));await clear(A);
await A.evaluate(()=>{PL={i:1,v:'pas',t:'test'};placeDone('net','ok');});await A.waitForTimeout(2800);console.log('ʻofe trouvé',await A.evaluate(()=>[vivoGet().ofe,bubbleEl.textContent.slice(0,40)]));await clear(A);
await A.evaluate(()=>{feathers=10;store.set('feathers',10);openInstr();$('#vvMake').click();});await A.waitForTimeout(300);console.log('fabriqué',await A.evaluate(()=>[vivoGet().made,feathers,!!$('#vvRetry'),!!$('#vvUupa')]));await A.evaluate(()=>$('#vvRetry').scrollIntoView());await A.screenshot({path:O+'vv0.png'});
// seconde chance au basket
await A.evaluate(()=>$('#vvRetry').click());await clear(A);await A.evaluate(()=>{openSport('b',null);$('#bkGo').click();});await A.waitForFunction(()=>BK.game&&BK.game.s,null,{timeout:5000});await A.evaluate(()=>BK.game.shoot(200,-320));await A.waitForTimeout(3000);
console.log('raté, mais pas compté',await A.evaluate(()=>[BK.res.length,$('#bkTxt').textContent.slice(-40),vivoGet().retry]));await A.screenshot({path:O+'vv1.png'});await A.waitForTimeout(2500);await A.evaluate(()=>BK.game.shoot(200,-320));await A.waitForFunction(()=>BK.res.length===1,null,{timeout:9000});console.log('le suivant compte',await A.evaluate(()=>BK.res.join()));await A.evaluate(()=>bkQuit());await clear(A);
// le lendemain : ʻūʻupa
await A.evaluate(()=>{const V=vivoGet();V.day='2026-01-01';store.set('vivo',V);openInstr();$('#vvUupa').click();});await A.waitForTimeout(2600);console.log('ʻūʻupa',await A.evaluate(()=>[!!birdEl.querySelector('.uupa'),bubbleEl.textContent.slice(0,40)]));await clear(A);await A.screenshot({path:O+'vv2.png'});
await A.evaluate(()=>openInstr());console.log('offrir possible',await A.evaluate(()=>!!$('#vvFr')));await A.evaluate(()=>document.querySelector('#vvFr [data-f="BBBB3333"]').click());await A.waitForTimeout(400);console.log('envoyé',JSON.stringify(db.visits.BBBB3333),await A.evaluate(()=>!birdEl.querySelector('.uupa')));
await B.evaluate(()=>pollVisits());let ok=false;for(let i=0;i<20;i++){await B.waitForTimeout(2000);ok=await B.evaluate(()=>{if(RING.open)closeRing();return !!birdEl.querySelector('.uupa');});if(ok)break;}console.log('Hina a le ʻūʻupa',ok,await B.evaluate(()=>JSON.stringify(uupaGet())));await B.evaluate(()=>bubbleEl.classList.remove('show'));await B.screenshot({path:O+'vv3.png'});
console.log('errs',A.errs,B.errs);await b.close();})();
