# Patch "le manu porte son instrument sur le dos". Dépend de instr-patch (et vivo-patch s'il est là).
# Usage : python3 porter_patch.py <site>/index.html <manu-ora.html>
import sys
for path in sys.argv[1:]:
    s=open(path,encoding='utf8').read()
    def rep(a,b,n=1):
        global s
        assert s.count(a)==n,(path,a[:70],s.count(a))
        s=s.replace(a,b)
    assert 'function openInstr(' in s, 'appliquer instr-patch avant'
    rep(".pepes{position:absolute;",""".carry{position:absolute;left:2%;top:34%;width:58%;height:34%;pointer-events:none;transform:rotate(-28deg);transform-origin:60% 50%}
.carry svg{width:100%;height:100%;overflow:visible}
.bird.flying .carry{transform:rotate(-12deg)}
.pepes{position:absolute;""")
    new = r"""/* ---------- le manu porte son instrument sur le dos ---------- */
let carryCw=0;
function carryWeave(x,y,w,h,col,clip){ let o=''; for(let k=0;k<w;k+=3.2) o+=`<path d="M${(x+k).toFixed(1)} ${y} l${(h*.45).toFixed(1)} ${h}" stroke="${col}" stroke-width=".6" opacity=".55"/>`; for(let k=0;k<w;k+=3.2) o+=`<path d="M${(x+k+h*.45).toFixed(1)} ${y} l${(-h*.45).toFixed(1)} ${h}" stroke="${col}" stroke-width=".6" opacity=".35"/>`; if(clip){ const id='cw'+(++carryCw); return `<clipPath id="${id}">${clip}</clipPath><g clip-path="url(#${id})">${o}</g>`; } return o; }
function carryMini(id,fin,sty){ sty=sty||'cord'; const w=fin==='nacre'?'#8A5A2B':'#A8743A', d='#5C3A1E', pearl=fin==='nacre'?'<circle cx="22" cy="15" r="2.2" fill="#DCE6EA" stroke="#9FB3BC" stroke-width=".6"/>':'', tat=(fin==='grav'||fin==='nacre')?`<path d="M14 18 l3 -3 l3 3 l3 -3 l3 3" stroke="${d}" stroke-width=".8" fill="none"/>`:'';
  const braid=(dd)=>`<path d="${dd}" stroke="#8E2A1E" stroke-width="2.6" fill="none" stroke-linecap="round"/><path d="${dd}" stroke="#F2C94C" stroke-width="1.3" fill="none" stroke-dasharray="1.6 2" stroke-linecap="round"/>`;
  const tassel=(x,y)=>`<circle cx="${x}" cy="${y}" r="2.2" fill="#8E2A1E"/><path d="M${x-1.5} ${y+1.5} l-1 6 M${x} ${y+2} v6.5 M${x+1.5} ${y+1.5} l1 6" stroke="#E4583F" stroke-width=".9" stroke-linecap="round"/><circle cx="${x}" cy="${y+8.5}" r="1" fill="#F2C94C"/>`;
  const band=(x,y,h)=>`<rect x="${x}" y="${y}" width="2.6" height="${h}" rx=".8" fill="#8E2A1E"/><rect x="${x+.6}" y="${y}" width="1.2" height="${h}" fill="#F2C94C" opacity=".8"/>`;
  const shell=(x,y)=>`<ellipse cx="${x}" cy="${y}" rx="2.4" ry="1.8" fill="#FFF6E3" stroke="#C9B890" stroke-width=".5"/><path d="M${x-1.6} ${y} h3.2" stroke="#C9B890" stroke-width=".4"/>`;
  const fara='#D9BE7A', fd='#9A7A3B';
  if(sty==='etui'){ const strap=`<path d="M6 4 Q30 30 54 4" stroke="${fd}" stroke-width="2.4" fill="none"/>`;
    if(id==='uke') return `<svg viewBox="0 0 60 30" aria-hidden="true">${strap}<rect x="44" y="12" width="12" height="5" rx="2" fill="${w}" stroke="${d}" stroke-width=".8"/><rect x="54" y="11" width="6" height="7" rx="1.5" fill="${w}" stroke="${d}" stroke-width=".8"/><path d="M4 15 q0 -12 13 -12 q10 0 16 7 h13 v9 h-13 q-6 7 -16 7 q-13 0 -13 -11z" fill="${fara}" stroke="${fd}" stroke-width="1"/>${carryWeave(0,3,48,24,fd,'<path d="M4 15 q0 -12 13 -12 q10 0 16 7 h13 v9 h-13 q-6 7 -16 7 q-13 0 -13 -11z"/>')}<path d="M33 10 q-4 5 0 9" stroke="${fd}" stroke-width="1" fill="none"/>${shell(30,14.5)}</svg>`;
    if(id==='toere') return `<svg viewBox="0 0 60 30" aria-hidden="true">${strap}<ellipse cx="6" cy="15" rx="3" ry="6.5" fill="#C99A5B" stroke="${d}" stroke-width=".7"/><rect x="7" y="7" width="48" height="16" rx="5" fill="${fara}" stroke="${fd}" stroke-width="1"/>${carryWeave(4,7,54,16,fd,'<rect x="7" y="7" width="48" height="16" rx="5"/>')}<path d="M7 11 h48 M7 19 h48" stroke="#8E2A1E" stroke-width=".9" opacity=".7"/>${shell(31,15)}<path d="M44 3 l10 8 M50 1 l7 9" stroke="#8A5A2B" stroke-width="2" stroke-linecap="round"/></svg>`;
    if(id==='pahu') return `<svg viewBox="0 0 60 30" aria-hidden="true">${strap}<path d="M12 6 h34 l-3 22 h-28z" fill="${fara}" stroke="${fd}" stroke-width="1"/>${carryWeave(6,6,46,22,fd,'<path d="M12 6 h34 l-3 22 h-28z"/>')}<path d="M12 6 q17 -6 34 0" fill="${fara}" stroke="${fd}" stroke-width="1"/><path d="M14 6 q15 5 30 0" stroke="#8E2A1E" stroke-width="1.2" fill="none"/>${tassel(44,7)}</svg>`;
    return `<svg viewBox="0 0 60 30" aria-hidden="true">${strap}<rect x="3" y="11" width="50" height="8" rx="4" fill="${fara}" stroke="${fd}" stroke-width="1"/>${carryWeave(0,11,56,8,fd,'<rect x="3" y="11" width="50" height="8" rx="4"/>')}<rect x="51" y="12" width="6" height="6" rx="3" fill="#D9C27A" stroke="#8A7A3B" stroke-width=".8"/>${tassel(6,18)}</svg>`; }
  if(id==='uke') return `<svg viewBox="0 0 60 30" aria-hidden="true">${braid('M6 5 Q30 30 55 6')}<rect x="24" y="12" width="32" height="5" rx="2" fill="${w}" stroke="${d}" stroke-width=".8"/><rect x="54" y="11" width="6" height="7" rx="1.5" fill="${w}" stroke="${d}" stroke-width=".8"/><ellipse cx="16" cy="14.5" rx="12" ry="9.5" fill="${w}" stroke="${d}" stroke-width="1"/><circle cx="16" cy="14.5" r="4" fill="#F1DDB0" stroke="${d}" stroke-width=".7"/>${tat}${pearl}<path d="M10 13.5 H58 M10 15.5 H58" stroke="#3B8C58" stroke-width=".4"/>${band(46,10.5,8)}${tassel(48,19)}</svg>`;
  if(id==='toere') return `<svg viewBox="0 0 60 30" aria-hidden="true">${braid('M4 6 Q30 30 56 6')}<rect x="4" y="8" width="52" height="14" rx="6" fill="${w}" stroke="${d}" stroke-width="1"/><ellipse cx="7" cy="15" rx="3" ry="6.5" fill="#C99A5B" stroke="${d}" stroke-width=".7"/><path d="M14 9.5 H50" stroke="${d}" stroke-width="2" stroke-linecap="round"/>${tat}${pearl}${band(16,7.5,15)}${band(42,7.5,15)}${tassel(43,23)}<path d="M40 3 l12 9 M48 1 l8 10" stroke="#8A5A2B" stroke-width="2" stroke-linecap="round"/></svg>`;
  if(id==='pahu') return `<svg viewBox="0 0 60 30" aria-hidden="true">${braid('M8 5 Q30 30 52 5')}<path d="M14 4 h30 l-3 24 h-24z" fill="${w}" stroke="${d}" stroke-width="1"/><ellipse cx="29" cy="4" rx="15" ry="3" fill="#F1E2C0" stroke="${d}" stroke-width=".8"/><path d="M17 7 l4 18 M23 7 l2 18 M29 7 v18 M35 7 l-2 18 M41 7 l-4 18" stroke="#8A6A3B" stroke-width=".7"/>${pearl}<path d="M15 14 h28" stroke="#8E2A1E" stroke-width="2"/><path d="M15 14 h28" stroke="#F2C94C" stroke-width=".9" stroke-dasharray="1.6 2"/>${tassel(43,15)}</svg>`;
  return `<svg viewBox="0 0 60 30" aria-hidden="true">${braid('M4 6 Q30 30 56 6')}<rect x="4" y="12" width="52" height="6" rx="3" fill="#D9C27A" stroke="#8A7A3B" stroke-width="1"/><circle cx="24" cy="15" r="1.2" fill="#5C4A1E"/><circle cx="34" cy="15" r="1.2" fill="#5C4A1E"/><circle cx="44" cy="15" r="1.2" fill="#5C4A1E"/>${band(10,11,8)}${band(50,11,8)}${tassel(11,19)}</svg>`; }
function carryOwned(id){ if(id==='vivo'){ try{ return !!vivoGet().made; }catch(e){ return false; } } return !!insGet()[id]; }
function carryRender(){ try{ const f=$('#birdFlip'); if(!f) return; let el=f.querySelector('.carry'); const id=cfg.carry; if(!id || !carryOwned(id)){ if(el) el.remove(); return; } if(getComputedStyle(f).position==='static') f.style.position='relative'; if(!el){ el=document.createElement('div'); el.className='carry'; f.insertBefore(el, f.firstChild); } const fin=id==='vivo'?'nat':((insGet()[id]||{}).fin||'nat'); const sty=(cfg.carryStyle==='etui' && store.get('etuiMade',false))?'etui':'cord'; el.innerHTML=carryMini(id,fin,sty); el.dataset.id=id+fin+sty; }catch(e){} }
function carrySet(id){ cfg.carry = cfg.carry===id ? '' : id; try{ saveCfg(); }catch(e){ store.set('cfg',cfg); } carryRender(); toast(cfg.carry ? cfg.name+' porte '+({uke:'son ʻukulele',toere:'son tōʻere',pahu:'son pahu',vivo:'son vivo'}[id])+' sur le dos' : cfg.name+' pose son instrument'); }
function carryBtn(id){ return `<button class="btn sm" data-carry="${id}">${cfg.carry===id?'Le poser':'Porter sur le dos'}</button>`; }
{ const _rb=renderBird; renderBird=function(){ const r=_rb.apply(this,arguments); carryRender(); return r; };
  const _oi=openInstr; openInstr=function(){ const r=_oi.apply(this,arguments); try{ const O=insGet(); sheetInner.querySelectorAll('[data-fin]').forEach(b=>{ const id=b.dataset.fin; if(O[id] && !b.parentNode.querySelector('[data-carry]')) b.insertAdjacentHTML('afterend',carryBtn(id)); }); try{ if(vivoGet().made){ const h=[...sheetInner.querySelectorAll('h3')].find(x=>/Le vivo/.test(x.textContent)); if(h && !h.parentNode.querySelector('[data-carry]')) h.insertAdjacentHTML('afterend',`<div class="row">${carryBtn('vivo')}</div>`); } }catch(e){}
      sheetInner.querySelectorAll('[data-carry]').forEach(b=>b.onclick=()=>{ carrySet(b.dataset.carry); openInstr(); });
      if(cfg.carry && carryOwned(cfg.carry)){ const made=store.get('etuiMade',false), st=sheetInner.querySelector('.stack'), fin=cfg.carry==='vivo'?'nat':((insGet()[cfg.carry]||{}).fin||'nat'); if(st){ st.insertAdjacentHTML('afterbegin',`<div class="card flat"><div class="eyebrow">Comment ${esc(cfg.name)} le porte</div><div style="display:flex;gap:10px"><button class="pans ${(cfg.carryStyle||'cord')==='cord'?'good':''}" data-sty="cord" style="flex:1;align-items:center;text-align:center"><span style="width:100%;height:46px;display:block">${carryMini(cfg.carry,fin,'cord')}</span><b>Cordelette tressée</b><span class="small muted">rouge et jaune</span></button><button class="pans ${cfg.carryStyle==='etui'&&made?'good':''}" data-sty="etui" style="flex:1;align-items:center;text-align:center"><span style="width:100%;height:46px;display:block">${carryMini(cfg.carry,fin,'etui')}</span><b>Étui en fara</b><span class="small muted">${made?'tressé':'2 fara du coffre, une fois'}</span></button></div></div>`);
        st.querySelectorAll('[data-sty]').forEach(b=>b.onclick=()=>{ const v=b.dataset.sty; if(v==='etui' && !store.get('etuiMade',false)){ if((garden.store.fara||0)<2){ toast('Il faut 2 fara récoltés pour tresser lʼétui'); return; } garden.store.fara-=2; saveGarden(); store.set('etuiMade',true); toast('Étui en fara tressé'); } cfg.carryStyle=v; try{ saveCfg(); }catch(e){ store.set('cfg',cfg); } carryRender(); openInstr(); }); } }
    }catch(e){} return r; }; }
setTimeout(carryRender,300);

"""
    rep("/* ---------- install button ---------- */", new+"/* ---------- install button ---------- */")
    open(path,'w',encoding='utf8').write(s)
    print('ok',path)
