# Patch "La route (code de la route, vélo ou scooter) en ville + Te pō, la soirée : garder l'œil sur son verre".
# Dépend de dock-patch. Usage : python3 route_patch.py <site>/index.html <manu-ora.html>
import sys
for path in sys.argv[1:]:
    s=open(path,encoding='utf8').read()
    def rep(a,b,n=1):
        global s
        assert s.count(a)==n,(path,a[:70],s.count(a))
        s=s.replace(a,b)
    assert 'function dockRender(' in s, 'appliquer dock-patch avant'
    rep("let curPlace=store.get('place','none');","PLACES.po={n:'Te pō', s:'la soirée', a:'Garder lʼœil', d:'Une soirée entre amis : profiter, et veiller les uns sur les autres.'};\nlet curPlace=store.get('place','none');")
    rep(".pepes{position:absolute;",""".rtfig{flex:none;height:170px;border-radius:16px;overflow:hidden;margin:8px 0;background:#CFE8F2}.rtfig svg{width:100%;height:100%;display:block}
.rtfig .rtveh{transition:transform 1.1s ease-in-out}.rtfig.go .rtveh{transform:translateX(150px)}.rtfig.stop .rtveh{transform:translateX(40px)}.rtfig.bad .rtveh{transform:translateX(120px)}
.rtfig .rtwarn{opacity:0;transition:opacity .3s .7s}.rtfig.bad .rtwarn{opacity:1}
.rtbar{flex:none;height:6px;border-radius:3px;background:var(--line,#d7e6e6);overflow:hidden;margin:4px 0 8px}.rtbar i{display:block;height:100%;background:#0F6E78;width:100%}
.quiet.po .qhint{display:none}
.pofig{flex:none;height:160px;border-radius:16px;overflow:hidden;margin:8px 0;background:#12304A}.pofig svg{width:100%;height:100%;display:block}
@media (prefers-reduced-motion:reduce){.rtfig .rtveh{transition:none}.rtbar i{transition:none!important}}
.pepes{position:absolute;""")
    rep("${curPlace==='oire'?'<button class=\"btn\" id=\"plMkt\">Te mātete : le marché de Papeete</button>':''}","${curPlace==='oire'?'<button class=\"btn\" id=\"plMkt\">Te mātete : le marché de Papeete</button><button class=\"btn\" id=\"plRoute\">La route : le code, à vélo ou en scooter</button>':''}")
    rep("const sf=$('#plSurf');","const rt=$('#plRoute'); if(rt) rt.onclick=()=>openRoute(); const sf=$('#plSurf');")
    new = r"""/* ---------- La route : le code de la route en situation (vélo ou scooter) ---------- */
ACT.route={t:'La route', p:'manao', d:'Les bons réflexes à vélo et en scooter.'};
ACT.soiree={t:'Garder lʼœil en soirée', p:'fetii', d:'Profiter, et veiller les uns sur les autres.'};
const RT=[
 {id:'orange', v:'bs', el:'light', q:'Le feu passe à lʼorange, tu es encore à bonne distance.', o:[['Jʼaccélère pour passer avant le rouge.',0],['Je mʼarrête : jʼai la place de freiner sans danger.',1],['Je klaxonne et je passe.',0]], r:'Le feu orange veut dire : arrête-toi, sauf si tu es déjà trop près pour freiner sans danger.'},
 {id:'stop', v:'bs', el:'stop', q:'Un panneau STOP au carrefour, et personne en vue.', o:[['Je ralentis et je passe, il nʼy a personne.',0],['Je mʼarrête complètement, je regarde des deux côtés, puis je repars.',1],['Je passe vite pour ne pas gêner.',0]], r:'Au STOP, on sʼarrête vraiment, pied à terre, même si la route a lʼair vide. On regarde, puis on repart.'},
 {id:'pieton', v:'bs', el:'cross', q:'Une mamie sʼengage sur le passage piéton devant toi.', o:[['Je la contourne par derrière.',0],['Je mʼarrête et je la laisse traverser.',1],['Je sonne ou je klaxonne pour quʼelle se dépêche.',0]], r:'Le piéton engagé sur le passage est prioritaire. On sʼarrête et on attend quʼil soit passé.'},
 {id:'casque', v:'s', el:'helmet', q:'Tu montes sur ton scooter. Il fait chaud, ton casque te gêne.', o:[['Je le pose sur la tête sans lʼattacher.',0],['Je lʼattache bien, la sangle sous le menton.',1],['Je le laisse, cʼest juste à côté.',0]], r:'Un casque non attaché sʼenvole au premier choc. Il ne protège que bien attaché, même pour cent mètres.'},
 {id:'casquev', v:'b', el:'helmet', q:'Tu pars à vélo chez un copain, deux rues plus loin.', o:[['Pas de casque, cʼest tout près.',0],['Je mets mon casque et je lʼattache.',1],['Je le mets dans mon sac.',0]], r:'La plupart des chutes arrivent près de chez soi. Le casque attaché protège la tête, et la tête, on nʼen a quʼune.'},
 {id:'trois', v:'s', el:'trio', q:'Deux copains veulent monter avec toi sur ton scooter.', o:[['On monte à trois, cʼest pas loin.',0],['Je prends un seul passager, avec un casque, sʼil y a une place prévue.',1],['On monte à trois mais je roule doucement.',0]], r:'Un scooter se conduit avec au plus le passager prévu par la place, casqué. À trois, on ne freine plus et on ne tient plus la route.'},
 {id:'porte', v:'b', el:'trio', q:'Ton ami veut monter sur ton porte-bagages ou ton guidon.', o:[['Allez, monte !',0],['Non : chacun son vélo, ou on marche à côté.',1],['Il monte, et on évite la route principale.',0]], r:'Un vélo est fait pour une personne. Avec un passager, on ne voit plus, on ne freine plus, et on tombe à deux.'},
 {id:'tel', v:'bs', el:'phone', q:'Ton téléphone vibre pendant que tu roules.', o:[['Je jette un œil, juste une seconde.',0],['Je continue, et je lis plus tard à lʼarrêt.',1],['Je réponds en tenant le guidon dʼune main.',0]], r:'Une seconde les yeux sur lʼécran, cʼest plusieurs mètres parcourus sans regarder. Le message attendra.'},
 {id:'camion', v:'bs', el:'truck', q:'Un camion devant toi met son clignotant à droite.', o:[['Je me faufile à sa droite pour passer avant.',0],['Je reste derrière lui et jʼattends quʼil ait tourné.',1],['Je klaxonne pour quʼil me laisse passer.',0]], r:'Sur sa droite, tu es dans son angle mort : il ne te voit pas. Si tu ne vois pas ses rétroviseurs, il ne te voit pas.'},
 {id:'rond', v:'bs', el:'round', q:'Tu arrives à un rond-point où des voitures tournent déjà.', o:[['Je mʼengage, cʼest moi qui arrive.',0],['Je cède le passage à ceux qui sont déjà dans le rond-point.',1],['Je passe au milieu, cʼest plus court.',0]], r:'Ceux qui sont déjà engagés dans le rond-point passent en premier. On attend un trou, puis on entre.'},
 {id:'nuit', v:'b', el:'night', q:'La nuit tombe, il te reste dix minutes de route.', o:[['Je roule dans le noir, je connais le chemin.',0],['Jʼallume mes lumières et je mets quelque chose de clair ou réfléchissant.',1],['Je roule sur le trottoir.',0]], r:'Le soir, il faut surtout être vu. Lumière devant, lumière derrière, et un vêtement clair.'},
 {id:'pluie', v:'bs', el:'rain', q:'Une grosse averse : la route est mouillée.', o:[['Je roule comme dʼhabitude.',0],['Je ralentis et je freine plus tôt.',1],['Jʼaccélère pour arriver avant dʼêtre trempé.',0]], r:'Sur une route mouillée, on glisse et on freine moins bien. On ralentit, et on garde plus de distance.'},
 {id:'ecout', v:'bs', el:'ears', q:'Tu as tes écouteurs, ta musique préférée commence.', o:[['Je monte le son.',0],['Je les enlève quand je roule, pour entendre la route.',1],['Je garde une seule oreille.',0]], r:'Sur la route, les oreilles servent à entendre un klaxon, une sirène, un moteur qui arrive. On garde la musique pour après.'}];
let RTS={};
function rtVeh(v){ return v==='s' ? `<g><circle cx="-14" cy="0" r="7" fill="#22323A"/><circle cx="16" cy="0" r="7" fill="#22323A"/><path d="M-20 -6 h30 l8 -14 h6 l-4 14 h4 v4 h-46z" fill="#E4583F"/><rect x="-10" y="-20" width="16" height="6" rx="2" fill="#22323A"/><g transform="translate(-8 -44) scale(.36)">${birdSVG(cfg,'rtv')}</g></g>` : `<g fill="none" stroke="#22323A" stroke-width="2.6"><circle cx="-16" cy="0" r="9"/><circle cx="16" cy="0" r="9"/><path d="M-16 0 l10 -14 h16 l6 14 M-6 -14 l-4 -6 M10 -14 l2 -8 h6"/></g><g transform="translate(-14 -46) scale(.36)">${birdSVG(cfg,'rtv')}</g>`; }
function rtFig(sc){ const veh=`<g class="rtveh"><g transform="translate(40 128)">${rtVeh(RTS.v)}</g></g>`, warn=`<g class="rtwarn"><circle cx="250" cy="44" r="16" fill="#F2C94C" stroke="#8A6A12" stroke-width="2"/><text x="250" y="51" text-anchor="middle" font-size="22" font-weight="900" fill="#5A3A00" font-family="sans-serif">!</text></g>`;
  const road=`<rect x="0" y="110" width="320" height="60" fill="#5C6B73"/><path d="M0 140 H320" stroke="#F4FAF8" stroke-width="3" stroke-dasharray="18 14"/><rect x="0" y="104" width="320" height="6" fill="#B9C4C9"/>`;
  let el='', bg=`<rect width="320" height="110" fill="#CFE8F2"/>`;
  if(sc.el==='light') el=`<rect x="232" y="30" width="18" height="46" rx="4" fill="#22323A"/><circle cx="241" cy="40" r="5" fill="#5A2A22"/><circle cx="241" cy="53" r="5" fill="#F2A23A"/><circle cx="241" cy="66" r="5" fill="#244A2E"/><rect x="239" y="76" width="4" height="34" fill="#22323A"/><path d="M226 110 v60" stroke="#F4FAF8" stroke-width="4"/>`;
  else if(sc.el==='stop') el=`<rect x="239" y="56" width="4" height="54" fill="#8A97A0"/><path d="M231 30 h20 l8 8 v20 l-8 8 h-20 l-8 -8 v-20z" fill="#C8402F" stroke="#fff" stroke-width="2"/><text x="241" y="52" text-anchor="middle" font-size="9" font-weight="900" fill="#fff" font-family="sans-serif">STOP</text><path d="M226 110 v60" stroke="#F4FAF8" stroke-width="5"/>`;
  else if(sc.el==='cross') el=`<g fill="#F4FAF8">${[0,1,2,3,4].map(i=>`<rect x="${214+i*14}" y="110" width="8" height="60"/>`).join('')}</g><g transform="translate(244 124)"><circle cx="0" cy="-26" r="6" fill="#C99A6B"/><path d="M-6 -18 h12 l2 22 h-16z" fill="#7FB2C9"/><path d="M-4 4 l-2 12 M4 4 l2 12" stroke="#22323A" stroke-width="2.4"/><path d="M8 -12 l6 16" stroke="#8A5A2B" stroke-width="2"/><path d="M-6 -30 q6 -6 12 0" fill="#E9E9E9"/></g>`;
  else if(sc.el==='helmet') el=`<g transform="translate(240 70)"><path d="M-22 10 q0 -30 22 -30 q22 0 22 30z" fill="#2F80D8" stroke="#16303B" stroke-width="2"/><path d="M-10 10 q10 18 20 0" fill="none" stroke="#16303B" stroke-width="2.4"/><rect x="-24" y="8" width="48" height="5" rx="2" fill="#16303B"/></g>`;
  else if(sc.el==='trio') el=`<g transform="translate(230 92)">${[0,1].map(i=>`<g transform="translate(${i*26} 0)"><circle cx="0" cy="-22" r="7" fill="#C99A6B"/><path d="M-7 -14 h14 l2 18 h-18z" fill="${i?'#F2C94C':'#3B8C58'}"/></g>`).join('')}<text x="13" y="-38" text-anchor="middle" font-size="12" font-weight="800" fill="#16303B" font-family="sans-serif">« On monte ! »</text></g>`;
  else if(sc.el==='phone') el=`<g transform="translate(236 40)"><rect x="-14" y="-24" width="28" height="48" rx="5" fill="#22323A"/><rect x="-11" y="-19" width="22" height="34" fill="#BFE6F5"/><rect x="-8" y="-12" width="16" height="6" rx="2" fill="#fff"/><path d="M-22 -10 q-6 10 0 20 M22 -10 q6 10 0 20" stroke="#E4583F" stroke-width="2" fill="none"/></g>`;
  else if(sc.el==='truck') el=`<g transform="translate(170 76)"><rect x="0" y="0" width="90" height="44" rx="4" fill="#F4FAF8" stroke="#16303B" stroke-width="2"/><rect x="90" y="12" width="30" height="32" rx="4" fill="#2F80D8" stroke="#16303B" stroke-width="2"/><rect x="100" y="16" width="14" height="12" fill="#BFE6F5"/><circle cx="20" cy="48" r="8" fill="#22323A"/><circle cx="104" cy="48" r="8" fill="#22323A"/><circle cx="121" cy="38" r="4" fill="#F2A23A"/><path d="M128 30 l14 0 l-5 -5 M142 30 l-5 5" stroke="#F2A23A" stroke-width="3" fill="none"/></g><path d="M20 152 q60 -30 150 -30" stroke="#C8402F" stroke-width="2" stroke-dasharray="4 5" fill="none" opacity=".7"/>`;
  else if(sc.el==='round') { bg=`<rect width="320" height="110" fill="#9CCB7A"/>`; el=`<circle cx="230" cy="110" r="70" fill="#5C6B73"/><circle cx="230" cy="110" r="30" fill="#7FB661"/><circle cx="230" cy="110" r="50" fill="none" stroke="#F4FAF8" stroke-width="2" stroke-dasharray="8 8"/><g transform="translate(230 54)"><rect x="-16" y="-8" width="32" height="16" rx="4" fill="#F2C94C"/></g><g transform="translate(286 104)"><rect x="-8" y="-16" width="16" height="32" rx="4" fill="#7FB2C9"/></g>`; }
  else if(sc.el==='night') { bg=`<rect width="320" height="110" fill="#12304A"/><circle cx="270" cy="30" r="10" fill="#FFF1C4"/>`; el=`<rect x="200" y="40" width="4" height="70" fill="#8A97A0"/><path d="M200 42 h20" stroke="#8A97A0" stroke-width="4"/><path d="M212 46 l-20 64 h40z" fill="#FFF3C4" opacity=".25"/>`; }
  else if(sc.el==='rain') { bg=`<rect width="320" height="110" fill="#9DAAB5"/>`; el=`<g stroke="#EEF4F7" stroke-width="1.6" opacity=".8">${Array.from({length:22},(_,i)=>`<path d="M${(i*29)%320} ${(i*37)%100} l-4 12"/>`).join('')}</g><ellipse cx="200" cy="150" rx="40" ry="6" fill="#8FA7B5" opacity=".7"/>`; }
  else if(sc.el==='ears') el=`<g transform="translate(240 56)"><path d="M-20 10 q0 -30 20 -30 q20 0 20 30" stroke="#22323A" stroke-width="4" fill="none"/><rect x="-26" y="4" width="12" height="18" rx="5" fill="#22323A"/><rect x="14" y="4" width="12" height="18" rx="5" fill="#22323A"/><text x="40" y="-6" font-size="18" fill="#2F80D8">♪</text></g>`;
  return `<svg viewBox="0 0 320 170" role="img" aria-label="${esc(sc.q)}">${bg}${road}${el}${veh}${warn}</svg>`; }
function openRoute(){ RTS={i:-1}; openSheet(`<div class="head"><div><div class="eyebrow">Te ʻoire · la ville</div><h2>La route</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div><p>Cinq situations sur la route, cinq choix. Tu as le temps de réfléchir, mais pas trop : comme en vrai.</p><p>Tu roules en…</p><div class="bkpick" style="display:grid;gap:10px"><button class="btn" data-v="b" style="display:block;width:100%;text-align:left"><b>Vélo</b></button><button class="btn" data-v="s" style="display:block;width:100%;text-align:left"><b>Scooter</b><br><span class="small muted">À partir de 14 ans, avec le BSR.</span></button></div><p class="small muted">Ce jeu montre les bons réflexes. Pour les règles exactes, cʼest le code de la route de la Polynésie et ton auto-école qui font foi.</p>`);
  $('#sx').onclick=closeSheet; sheetInner.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{ const v=b.dataset.v; const pool=RT.filter(x=>x.v.includes(v)).sort(()=>Math.random()-.5); RTS={v, list:pool.slice(0,5), i:0, ok:0, pick:null}; rtStep(); }); }
function rtStep(){ clearInterval(RTS.iv); const sc=RTS.list[RTS.i];
  if(!sc){ const n=RTS.ok; openSheet(`<div class="head"><div><div class="eyebrow">Te ʻoire · la ville</div><h2>${n} bon${n>1?'s':''} réflexe${n>1?'s':''} sur 5</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div><p>${n>=4?'Belle conduite. Tu roules avec la tête, pas seulement avec les mains.':n>=2?'Des bons réflexes, et quelques-uns à revoir. Cʼest pour ça quʼon sʼentraîne ici, et pas sur la vraie route.':'La route, ça sʼapprend. Rejoue : les situations changent à chaque fois.'}</p><div class="note">Sur la route, personne nʼest pressé au point de risquer sa tête. Dans le doute, on ralentit.</div><button class="btn primary" id="rtEnd">Māuruuru</button><button class="btn ghost" id="rtAgain">Rejouer</button>`); $('#sx').onclick=closeSheet; $('#rtAgain').onclick=openRoute; $('#rtEnd').onclick=()=>placeDone('route','Casque attaché, yeux sur la route. Bonne route !'); return; }
  const ord=RTS.ord||(RTS.ord=[0,1,2].sort(()=>Math.random()-.5)); const done=RTS.pick!==null;
  openSheet(`<div class="head"><div><div class="eyebrow">La route · ${RTS.v==='s'?'en scooter':'à vélo'} · ${RTS.i+1} sur 5</div><h2>${done?(sc.o[RTS.pick]&&sc.o[RTS.pick][1]?'Bon réflexe':'Attention'):'Que fais-tu ?'}</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div><div class="rtfig" id="rtFig">${rtFig(sc)}</div><p>${sc.q}</p>${done?'':'<div class="rtbar" aria-hidden="true"><i id="rtBar"></i></div>'}<div class="stack" id="rtO">${ord.map(i=>{ const o=sc.o[i], on=done&&(i===RTS.pick||o[1]); return `<button class="pans ${on?(o[1]?'good':'meh'):''}" data-v="${i}" ${done?'disabled':''}>${o[0]}</button>`; }).join('')}</div>${done?`<div class="card flat"><p class="small">${RTS.pick<0?'Tu as hésité trop longtemps. Sur la route, dans le doute, on ralentit et on sʼarrête. ':''}${sc.r}</p></div><button class="btn primary" id="rtNext">${RTS.i<4?'Situation suivante':'Voir le résultat'}</button>`:''}`);
  $('#sx').onclick=()=>{ clearInterval(RTS.iv); closeSheet(); };
  if(done){ const f=$('#rtFig'), good=RTS.pick>=0 && sc.o[RTS.pick][1]; requestAnimationFrame(()=>requestAnimationFrame(()=>{ f.classList.add(good?(sc.el==='light'||sc.el==='stop'||sc.el==='cross'||sc.el==='truck'||sc.el==='round'?'stop':'go'):'bad'); })); $('#rtNext').onclick=()=>{ RTS.i++; RTS.pick=null; RTS.ord=null; rtStep(); }; return; }
  const T=9000, t0=Date.now(), bar=$('#rtBar'); RTS.iv=setInterval(()=>{ const k=1-(Date.now()-t0)/T; if(bar) bar.style.width=Math.max(0,k*100)+'%'; if(k<=0){ clearInterval(RTS.iv); RTS.pick=-1; rtStep(); } },100);
  $('#rtO').addEventListener('click', e=>{ const b=e.target.closest('[data-v]'); if(!b) return; clearInterval(RTS.iv); RTS.pick=+b.dataset.v; if(sc.o[RTS.pick][1]) RTS.ok++; rtStep(); }); }

/* ---------- Te pō, la soirée : garder lʼœil sur son verre et sur ses amis ---------- */
const SOIR=[
 {id:'verre', fig:'offer', q:'Un garçon que tu ne connais pas te tend un verre déjà rempli : « Tiens, cʼest pour toi ! »', o:[['Je le bois, pour être poli·e.',0],['Je dis « merci, non » et je vais me servir moi-même.',1],['Je le prends et je le pose plus loin sans rien dire.',2]], r:'Un verre, on le prend quand on lʼa vu servir, ou quand il est fermé. Dire non à un verre, ce nʼest pas impoli.'},
 {id:'table', fig:'table', q:'Tu reviens de danser. Ton verre est resté seul sur la table.', o:[['Je le finis, cʼest le mien.',0],['Je le laisse, et je mʼen sers un nouveau.',1],['Je demande à quelquʼun sʼil lʼa surveillé.',2]], r:'Un verre laissé seul, on le laisse. On en reprend un, cʼest tout.'},
 {id:'cachet', fig:'pill', q:'Quelquʼun te propose un petit cachet : « Cʼest rien, juste pour sʼamuser. »', o:[['Jʼaccepte, pour ne pas passer pour un rabat-joie.',0],['Je dis non, et je vais retrouver mes amis.',1],['Je le prends « pour plus tard ».',0]], r:'Personne ne peut savoir ce quʼil y a vraiment dans un cachet, une poudre ou un « truc » quʼon te tend. « Non », cʼest une réponse complète.'},
 {id:'malaise', fig:'friend', q:'Ton amie nʼa bu quʼun seul verre, mais elle titube et parle bizarrement.', o:[['Je la laisse se reposer seule dans un coin.',0],['Je reste avec elle, je préviens un adulte de confiance, et on appelle de lʼaide si ça ne va pas.',1],['Jʼattends que ça passe en continuant à danser.',0]], r:'Des signes dʼivresse après presque rien, ça peut vouloir dire que son verre a été trafiqué. On ne la laisse jamais seule, et on demande de lʼaide.'},
 {id:'raccompagne', fig:'stranger', q:'Un inconnu propose de raccompagner ton amie qui ne va pas bien.', o:[['Jʼaccepte, il a lʼair gentil.',0],['Je refuse : elle rentre avec nous, ou avec quelquʼun de sa famille.',1],['Je la laisse décider seule.',0]], r:'Quelquʼun qui ne va pas bien ne part pas avec un inconnu. Elle rentre avec ses amis ou sa famille.'},
 {id:'bob', fig:'group', q:'Avant la soirée, vous vous organisez avec tes amis.', o:[['Chacun rentre comme il peut.',0],['On désigne quelquʼun qui reste clair, et on rentre ensemble.',1],['On verra sur place.',0]], r:'On arrive ensemble, on repart ensemble. Et quelquʼun garde la tête claire pour tout le monde.'}];
let SOIRS={};
function poFig(sc){ const lights=`<path d="M0 22 Q160 46 320 22" stroke="#5C4A2E" stroke-width="1" fill="none"/>${[0,1,2,3,4,5,6,7].map(i=>`<circle cx="${20+i*40}" cy="${24+Math.sin(i/7*Math.PI)*16}" r="3.5" fill="${['#F2C94C','#E4583F','#2BB3C0','#F7A8C4'][i%4]}"/>`).join('')}`;
  const me=`<g transform="translate(40 66) scale(.6)">${birdSVG(cfg,'po')}</g>`;
  const person=(x,col,flip)=>`<g transform="translate(${x} 150)"><circle cx="0" cy="-60" r="11" fill="#6E7F8D"/><path d="M-14 -48 h28 l4 48 h-36z" fill="${col}"/></g>`;
  const glass=(x,y,c)=>`<g transform="translate(${x} ${y})"><path d="M-7 -16 h14 l-2 18 h-10z" fill="${c}" stroke="#F4FAF8" stroke-width="1.2"/><path d="M-6 -10 h12" stroke="#F4FAF8" stroke-width=".8" opacity=".6"/></g>`;
  let el='';
  if(sc.fig==='offer') el=person(230,'#4A5A66')+glass(205,104,'#F2A23A')+`<path d="M216 96 l-10 4" stroke="#6E7F8D" stroke-width="4" stroke-linecap="round"/>`;
  else if(sc.fig==='table') el=`<rect x="170" y="110" width="110" height="8" rx="3" fill="#8A5A2B"/><rect x="186" y="118" width="6" height="34" fill="#5C3A1E"/><rect x="258" y="118" width="6" height="34" fill="#5C3A1E"/>`+glass(224,108,'#F7A8C4')+`<circle cx="224" cy="80" r="14" fill="none" stroke="#F2C94C" stroke-width="2" stroke-dasharray="4 4"/>`;
  else if(sc.fig==='pill') el=person(230,'#4A5A66')+`<g transform="translate(204 100)"><ellipse rx="10" ry="5" fill="#F4FAF8"/><path d="M0 -5 v10" stroke="#B9C4C9"/></g><path d="M216 96 l-6 4" stroke="#6E7F8D" stroke-width="4" stroke-linecap="round"/>`;
  else if(sc.fig==='friend') el=`<g transform="translate(220 150) rotate(-10)"><circle cx="0" cy="-60" r="11" fill="#C99A6B"/><path d="M-14 -48 h28 l4 48 h-36z" fill="#F7A8C4"/></g><text x="246" y="70" font-size="16" fill="#F2C94C" font-family="sans-serif">~ ~</text>`+glass(270,148,'#F2A23A');
  else if(sc.fig==='stranger') el=`<g transform="translate(200 150) rotate(-8)"><circle cx="0" cy="-60" r="11" fill="#C99A6B"/><path d="M-14 -48 h28 l4 48 h-36z" fill="#F7A8C4"/></g>`+person(256,'#4A5A66')+`<path d="M242 104 l-28 0" stroke="#6E7F8D" stroke-width="4" stroke-linecap="round"/>`;
  else el=person(190,'#3B8C58')+person(236,'#F2C94C')+person(282,'#2F80D8')+`<g transform="translate(236 70)"><circle r="12" fill="#F4FAF8"/><text y="5" text-anchor="middle" font-size="12" font-weight="900" fill="#16303B" font-family="sans-serif">Bob</text></g>`;
  return `<svg viewBox="0 0 320 160" role="img" aria-label="${esc(sc.q)}"><rect width="320" height="160" fill="#12304A"/>${lights}<rect y="150" width="320" height="10" fill="#2A4C5A"/>${me}${el}</svg>`; }
function openSoiree(){ const pool=SOIR.slice(0,5).sort(()=>Math.random()-.5).slice(0,4).concat([SOIR[5]]); SOIRS={list:pool, i:0, ok:0, pick:null, ord:null};
  openSheet(`<div class="head"><div><div class="eyebrow">Te pō · la soirée</div><h2>Garder lʼœil</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div><p>Une soirée, cʼest fait pour sʼamuser. Et une bonne soirée, cʼest aussi une soirée où tout le monde rentre bien. Cinq petites situations.</p><div class="pofig">${poFig({fig:'group',q:'Une soirée entre amis'})}</div><button class="btn primary" id="poGo">Commencer</button>`);
  $('#sx').onclick=closeSheet; $('#poGo').onclick=poStep; }
function poStep(){ const sc=SOIRS.list[SOIRS.i];
  if(!sc){ openSheet(`<div class="head"><div><div class="eyebrow">Te pō · la soirée</div><h2>Trois réflexes à garder</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div>
    <div class="card flat"><p><b>1.</b> Un verre, je le prends quand je lʼai vu servir, ou fermé.</p></div><div class="card flat"><p><b>2.</b> Un verre laissé seul, je le laisse.</p></div><div class="card flat"><p><b>3.</b> On arrive ensemble, on repart ensemble. Personne ne reste seul.</p></div>
    <p class="small">Si un ami ne va pas bien, ce nʼest pas une honte de demander de lʼaide : un adulte de confiance, ou les numéros du bouton <b>Aide</b>.</p><button class="btn" id="poHelp">Ouvrir lʼAide</button><button class="btn primary" id="poEnd">Māuruuru</button>`);
    $('#sx').onclick=closeSheet; $('#poHelp').onclick=()=>{ closeSheet(); openCrisis(); }; $('#poEnd').onclick=()=>placeDone('soiree','Profite de tes soirées, et veillez les uns sur les autres.'); return; }
  const ord=SOIRS.ord||(SOIRS.ord=[0,1,2].sort(()=>Math.random()-.5)); const done=SOIRS.pick!==null, val=done?sc.o[SOIRS.pick][1]:0;
  openSheet(`<div class="head"><div><div class="eyebrow">Te pō · la soirée · ${SOIRS.i+1} sur 5</div><h2>${done?(val===1?'Bon réflexe':val===2?'Pas mal, mais…':'À revoir'):'Que fais-tu ?'}</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div><div class="pofig">${poFig(sc)}</div><p>${sc.q}</p><div class="stack" id="poO">${ord.map(i=>{ const o=sc.o[i], on=done&&(i===SOIRS.pick||o[1]===1); return `<button class="pans ${on?(o[1]===1?'good':'meh'):''}" data-v="${i}" ${done?'disabled':''}>${o[0]}</button>`; }).join('')}</div>${done?`<div class="card flat"><p class="small">${sc.r}</p></div><button class="btn primary" id="poNext">${SOIRS.i<4?'Suivant':'Voir les réflexes'}</button>`:''}`);
  $('#sx').onclick=closeSheet;
  if(done){ $('#poNext').onclick=()=>{ SOIRS.i++; SOIRS.pick=null; SOIRS.ord=null; poStep(); }; return; }
  $('#poO').addEventListener('click', e=>{ const b=e.target.closest('[data-v]'); if(!b) return; SOIRS.pick=+b.dataset.v; if(sc.o[SOIRS.pick][1]===1) SOIRS.ok++; poStep(); }); }
function poScene(){ const lights=Array.from({length:12},(_,i)=>`<circle class="hv-lamp" style="animation-delay:-${(i*.25).toFixed(2)}s" cx="${20+i*29}" cy="${250+Math.sin(i/11*Math.PI)*30}" r="5" fill="${['#F2C94C','#E4583F','#2BB3C0','#F7A8C4'][i%4]}"/>`).join('');
  let st=''; for(let i=0;i<40;i++) st+=`<circle cx="${(i*83)%360}" cy="${(i*47)%220}" r="${.6+(i%3)*.4}" fill="#fff" opacity=".5"/>`;
  return `<defs><linearGradient id="scSky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0B1533"/><stop offset="1" stop-color="#2A2A5C"/></linearGradient></defs><rect x="-1400" y="-700" width="3160" height="1340" fill="url(#scSky)"/>${st}
  <g fill="#1A2140"><rect x="-1400" y="300" width="3160" height="200"/><rect x="10" y="230" width="70" height="90"/><rect x="290" y="210" width="80" height="110"/></g><g fill="#F2C94C" opacity=".5"><rect x="22" y="246" width="10" height="12"/><rect x="50" y="246" width="10" height="12"/><rect x="304" y="226" width="10" height="12"/><rect x="334" y="258" width="10" height="12"/></g>
  <path d="M0 248 Q180 300 360 248" stroke="#5C4A2E" stroke-width="1.2" fill="none"/>${lights}
  <rect x="-1400" y="420" width="3160" height="900" fill="#3A3360"/><g opacity=".35">${[0,1,2,3,4,5].map(i=>`<ellipse cx="${30+i*60}" cy="470" rx="40" ry="8" fill="${['#E4583F','#2BB3C0','#F2C94C'][i%3]}"/>`).join('')}</g>
  <g transform="translate(80 400)"><rect x="-24" y="0" width="48" height="60" rx="6" fill="#22323A"/><circle cx="0" cy="20" r="12" fill="#3A4A56"/><circle cx="0" cy="20" r="5" fill="#16303B"/><circle cx="0" cy="46" r="7" fill="#3A4A56"/></g><g transform="translate(280 400)"><rect x="-24" y="0" width="48" height="60" rx="6" fill="#22323A"/><circle cx="0" cy="20" r="12" fill="#3A4A56"/><circle cx="0" cy="20" r="5" fill="#16303B"/><circle cx="0" cy="46" r="7" fill="#3A4A56"/></g>
  <g transform="translate(180 470)"><rect x="-50" y="-10" width="100" height="40" rx="6" fill="#8A5A2B"/><text x="0" y="12" text-anchor="middle" font-size="10" font-weight="800" fill="#FFF3D6" font-family="sans-serif">SOIRÉE</text></g>`; }
{ const _si=sceneInner; sceneInner=function(id){ return id==='po' ? poScene() : _si.apply(this,arguments); };
  const _pa=placeAct; placeAct=function(){ if(curPlace==='po'){ openSoiree(); return; } return _pa.apply(this,arguments); };
  const _rp=renderPlace; renderPlace=function(){ const r=_rp.apply(this,arguments); try{ const q=$('#quiet'), el=$('#dayScene'), ns=$('#nightSky'); if(q) q.classList.toggle('po', curPlace==='po'); if(q && el && curPlace==='po'){ if(el.dataset.p!=='po'){ el.innerHTML=poScene(); el.dataset.p='po'; } el.removeAttribute('hidden'); q.classList.add('scene','night'); if(ns) ns.setAttribute('hidden',''); try{ document.documentElement.setAttribute('data-theme','dark'); }catch(e){} } }catch(e){} return r; };
  const _rn=renderNight; renderNight=function(){ const r=_rn.apply(this,arguments); try{ if(curPlace==='po') renderPlace(); }catch(e){} return r; }; }
setTimeout(()=>{ try{ if(typeof QI!=='undefined'){ QI.po='<rect x="2" y="2" width="24" height="24" rx="7" fill="#2A2A5C"/><path d="M4 9 Q14 15 24 9" stroke="#C99A5B" stroke-width="1" fill="none"/><circle cx="7" cy="10" r="1.8" fill="#F2C94C"/><circle cx="14" cy="12" r="1.8" fill="#E4583F"/><circle cx="21" cy="10" r="1.8" fill="#2BB3C0"/><path d="M11 16 h6 l-1 7 h-4z" fill="#F7A8C4"/>'; QI.oeil='<path d="M3 14 q11 -11 22 0 q-11 11 -22 0z" fill="#fff" stroke="#16303B" stroke-width="1.6"/><circle cx="14" cy="14" r="4.5" fill="#2F80D8"/><circle cx="14" cy="14" r="2" fill="#16303B"/>'; QI.route='<rect x="2" y="2" width="24" height="24" rx="7" fill="#5C6B73"/><path d="M14 3 v4 M14 11 v4 M14 19 v4" stroke="#fff" stroke-width="2"/><circle cx="8" cy="20" r="3" fill="none" stroke="#F2C94C" stroke-width="1.6"/><circle cx="20" cy="20" r="3" fill="none" stroke="#F2C94C" stroke-width="1.6"/>'; QPL.po='Soirée';
      const _qa4=qActs; qActs=function(){ const a=_qa4.apply(this,arguments); if(curPlace==='oire') a.push({k:'route',l:'La route',t:'La route : le code, à vélo ou en scooter',go:openRoute}); if(curPlace==='po') return [{k:'oeil',l:'Garder lʼœil',t:'Garder lʼœil en soirée',go:openSoiree}]; return a; }; dockRender(); } }catch(e){} },250);

"""
    rep("/* ---------- install button ---------- */", new+"/* ---------- install button ---------- */")
    open(path,'w',encoding='utf8').write(s)
    print('ok',path)
