# Patch "les quatre pierres, le passage, Te reva (le monde du ciel) : nuages et vents" — base v91 + patch décors (scene-patch).
# Usage : python3 sky_patch.py <site>/index.html <manu-ora.html>
import sys
for path in sys.argv[1:]:
    s=open(path,encoding='utf8').read()
    def rep(a,b,n=1):
        global s
        assert s.count(a)==n,(path,a[:70],s.count(a))
        s=s.replace(a,b)
    rep("let curPlace=store.get('place','none');","const REVA_PLACE={n:'Te reva', s:'le monde du ciel', a:'Lire le ciel', d:'Les nuages et les vents : apprendre à lire le temps quʼil fait dehors, et celui quʼil fait dedans.'}; if(store.get('portal',false)) PLACES.reva=REVA_PLACE;\nlet curPlace=store.get('place','none');")
    rep(".pepes{position:absolute;",""".portal{position:fixed;inset:0;z-index:9000;background:radial-gradient(circle at 50% 46%,#2E6FB7 0%,#10254A 70%);display:grid;place-items:center;opacity:0;transition:opacity .8s;overflow:hidden}
.portal.on{opacity:1}.portal svg{width:min(92vw,420px);height:auto;overflow:visible}
.portal .pst{transform-box:fill-box;transform-origin:center;animation:pstRise 2.6s cubic-bezier(.3,.7,.3,1) both}
.portal .pring{transform-box:fill-box;transform-origin:center;animation:pRing 2.2s 2.6s ease-out both}
.portal .psky{transform-box:fill-box;transform-origin:center;animation:pRing 2.4s 3s ease-out both}
.portal .ptx{fill:#fff;font-family:var(--display);font-weight:700;text-anchor:middle;opacity:0;animation:pTx 1.2s 4.6s ease-out forwards}
.portal .pspin{transform-box:view-box;transform-origin:180px 190px;animation:pSpin 14s 2.6s linear infinite}
@keyframes pstRise{from{transform:translate(var(--fx),var(--fy)) scale(.5);opacity:0}30%{opacity:1}to{transform:none;opacity:1}}
@keyframes pRing{from{transform:scale(0);opacity:0}to{transform:scale(1);opacity:1}}
@keyframes pTx{to{opacity:1}}@keyframes pSpin{to{transform:rotate(360deg)}}
@media (prefers-reduced-motion:reduce){.portal .pst,.portal .pring,.portal .psky,.portal .ptx,.portal .pspin{animation:none;opacity:1}}
.skyfig{flex:none;height:150px;border-radius:16px;overflow:hidden;background:linear-gradient(#8CC6EE,#DDF1FA);margin:8px 0}.skyfig svg{width:100%;height:100%;display:block}
.rose{flex:none;position:relative;width:min(100%,300px);aspect-ratio:1;margin:8px auto}.rose svg{width:100%;height:100%}
.rose button{position:absolute;transform:translate(-50%,-50%);border:1.5px solid var(--line);background:var(--surface);border-radius:999px;padding:6px 10px;font-family:var(--display);font-weight:700;font-size:.82rem;color:var(--fg)}
.rose button.on{border-color:var(--lagoon);background:#E3F2F1}.rose button.good{border-color:var(--fern);background:rgba(59,140,88,.15)}
.stonerow{display:flex;gap:10px;align-items:center;margin:4px 0}.stonerow svg{width:30px;height:30px;flex:none}
.pepes{position:absolute;""")
    new = r"""/* ---------- les quatre pierres, le passage, Te reva : le monde du ciel (nuages et vents) ---------- */
const STONE={vai:{c:'#3B8C58',n:'la pierre verte de la vallée',w:'à la rivière'}, tai:{c:'#2BB3C0',n:'la pierre bleue du lagon',w:'sur la plage'}, oire:{c:'#E4583F',n:'la pierre rouge de la ville',w:'en ville'}, haapii:{c:'#F2C94C',n:'la pierre dorée de lʼécole',w:'dans la cour de lʼécole'}};
function stoneSVG(c){ return `<svg viewBox="0 0 30 30" aria-hidden="true"><path d="M15 2 L26 10 L22 26 L8 26 L4 10Z" fill="${c}" stroke="#16303B" stroke-width="1.2" stroke-linejoin="round"/><path d="M15 2 L15 14 L26 10 M15 14 L4 10 M15 14 L8 26 M15 14 L22 26" stroke="#fff" stroke-width="1" opacity=".55" fill="none"/></svg>`; }
function stonesGot(){ const o=store.get('stones',{}); return (o && typeof o==='object') ? o : {}; }
function stoneFull(id){ try{ if(typeof sceneSteps!=='function') return false; const st=sceneSteps(id); return st.length>0 && st.every(x=>x[0]); }catch(e){ return false; } }
let STQ={busy:false};
function stoneFree(){ return visitFree() && !bubbleEl.classList.contains('show') && !document.querySelector('.portal'); }
function stoneTick(){ try{ if(STQ.busy) return; const got=stonesGot(); const nw=Object.keys(STONE).find(k=>!got[k] && stoneFull(k));
    if(nw){ if(!stoneFree()) return; got[nw]=dayKey(Date.now()); store.set('stones',got); say(`Regarde ce que jʼai trouvé ${STONE[nw].w} : ${STONE[nw].n}. Je ne sais pas à quoi elle sert. Je la garde.`); return; }
    if(!store.get('portal',false) && Object.keys(STONE).every(k=>got[k])){ if(!stoneFree()) return; STQ.busy=true; setTimeout(portalOpen, 1500); } }catch(e){} }
function portalOpen(){ const d=document.createElement('div'); d.className='portal'; d.setAttribute('role','dialog'); d.setAttribute('aria-label','Un passage sʼouvre vers Te reva, le monde du ciel');
  const pos=[[180,70],[300,190],[180,310],[60,190]], from=[['-120px','260px'],['-240px','140px'],['0px','20px'],['240px','140px']];
  d.innerHTML=`<svg viewBox="0 0 360 440"><g class="psky"><circle cx="180" cy="190" r="96" fill="#BFE6F5"/><ellipse cx="150" cy="215" rx="46" ry="15" fill="#fff"/><ellipse cx="205" cy="200" rx="40" ry="14" fill="#fff" opacity=".9"/><circle cx="212" cy="150" r="17" fill="#FFE08A"/></g><circle class="pring" cx="180" cy="190" r="100" fill="none" stroke="#FFF3C4" stroke-width="5"/><g class="pspin">${Object.keys(STONE).map((k,i)=>`<g class="pst" style="--fx:${from[i][0]};--fy:${from[i][1]};animation-delay:${i*.35}s"><g transform="translate(${pos[i][0]-22} ${pos[i][1]-22}) scale(1.45)">${stoneSVG(STONE[k].c).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g></g>`).join('')}</g><text class="ptx" x="180" y="366" font-size="26">Te reva</text><text class="ptx" x="180" y="394" font-size="15" style="font-weight:600">Les quatre pierres ouvrent un passage vers le ciel.</text><text class="ptx" x="180" y="426" font-size="12" style="font-weight:600;opacity:.8">Touche pour entrer</text></svg>`;
  document.body.appendChild(d); requestAnimationFrame(()=>d.classList.add('on'));
  const end=()=>{ if(d.dataset.done) return; d.dataset.done='1'; store.set('portal',true); PLACES.reva=REVA_PLACE; d.classList.remove('on'); setTimeout(()=>{ d.remove(); STQ.busy=false; try{ if(cfg.night==='on'){ cfg.night='auto'; store.set('cfg',cfg); renderNight(); } if(!QUIET) setQuiet(true); }catch(e){} setPlace('reva'); say(isNight()?'Un nouveau lieu sʼest ouvert : Te reva, le monde du ciel. Tu le verras au matin.':'Nous voilà au-dessus des nuages. Ici, on apprend à lire le ciel. Et un peu le cœur, aussi.'); },800); };
  let ready=false; setTimeout(()=>{ ready=true; }, RM?600:5200); d.addEventListener('click',()=>{ if(ready) end(); }); setTimeout(end, RM?6000:16000); }
function revaDone(){ const o=store.get('reva',{}); return (o && typeof o==='object') ? o : {}; }
function revaScene(){ const R=revaDone(), cl=(x,y,s,o)=>`<g transform="translate(${x} ${y}) scale(${s})" fill="#fff" opacity="${o||1}"><ellipse cx="0" cy="0" rx="60" ry="20"/><ellipse cx="-30" cy="-14" rx="30" ry="20"/><ellipse cx="16" cy="-22" rx="36" ry="26"/><ellipse cx="50" cy="-8" rx="24" ry="16"/></g>`;
  return `<defs><linearGradient id="scSky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2E6FB7"/><stop offset=".55" stop-color="#8CC6EE"/><stop offset="1" stop-color="#DDF1FA"/></linearGradient></defs><rect x="-1400" y="-700" width="3160" height="1340" fill="url(#scSky)"/>
  <circle cx="286" cy="110" r="60" fill="#FFF3C4" opacity=".45"/><circle cx="286" cy="110" r="32" fill="#FFE08A"/>
  ${R.clouds?`<g fill="none" stroke-width="4" opacity=".6"><path d="M40 440 A150 150 0 0 1 340 440" stroke="#E4583F"/><path d="M44 440 A146 146 0 0 1 336 440" stroke="#F0A23A"/><path d="M48 440 A142 142 0 0 1 332 440" stroke="#F2C94C"/><path d="M52 440 A138 138 0 0 1 328 440" stroke="#3B8C58"/><path d="M56 440 A134 134 0 0 1 324 440" stroke="#2BB3C0"/><path d="M60 440 A130 130 0 0 1 320 440" stroke="#6C5FB5"/></g>`:''}
  <g opacity=".5" stroke="#fff" stroke-width="2.4" fill="none"><path class="sc-flow" d="M-20 250 q60 -18 120 0 t120 0 t140 -6"/><path class="sc-flow" style="animation-delay:-1.2s" d="M-20 330 q70 14 140 0 t150 4 t110 0"/></g>
  <g class="sc-cloud">${cl(-80,200,.8,.85)}</g><g class="sc-cloud" style="animation-delay:-44s">${cl(-60,300,.55,.8)}</g>
  <g transform="translate(180 476)"><ellipse cx="0" cy="0" rx="92" ry="30" fill="#7FD6DE"/><ellipse cx="0" cy="0" rx="92" ry="30" fill="none" stroke="#fff" stroke-width="2" stroke-dasharray="14 6" opacity=".9"/><ellipse cx="0" cy="-1" rx="76" ry="23" fill="#2BB3C0" opacity=".55"/><path d="M-56 2 Q-44 -22 -14 -18 Q0 -34 20 -20 Q50 -22 58 2 Q30 16 0 14 Q-34 16 -56 2Z" fill="#3B8C58"/><path d="M-30 -4 L-14 -18 L-4 -6 L10 -24 L24 -8 L36 -12" fill="none" stroke="#2A6B45" stroke-width="2"/><ellipse cx="70" cy="14" rx="9" ry="3.5" fill="#F1DDB0"/></g>
  <rect x="-1400" y="590" width="3160" height="60" fill="#EAF5FB"/><g fill="#CFE6F3">${cl(60,566,1.1).replace('fill="#fff"','')}${cl(290,572,1.2).replace('fill="#fff"','')}</g>${cl(20,590,1)}${cl(180,600,1.2)}${cl(330,592,1)}<g opacity=".9">${cl(100,632,1.3)}${cl(270,636,1.3)}${cl(-30,634,1.1)}</g>
  ${R.winds?`<g class="sc-bob"><path d="M96 150 l22 -30 l22 30 l-22 34z" fill="#E4583F" stroke="#8E1322" stroke-width="1.2"/><path d="M118 120 v64 M96 150 h44" stroke="#FFF3D6" stroke-width="1.4"/><path d="M118 184 q-10 18 4 34 t-2 36" fill="none" stroke="#16303B" stroke-width="1.2"/><path d="M114 204 l8 3 M119 224 l-8 3 M118 244 l8 3" stroke="#F2C94C" stroke-width="3" stroke-linecap="round"/></g>`:''}`; }
const SKYC=[
 {id:'cumulus', n:'Le cumulus', ty:'petit nuage blanc de beau temps', q:'Quʼannonce ce petit nuage blanc, bien rond ?', o:['Un orage dans lʼheure','Du beau temps','Une semaine de pluie'], ok:1, why:'Des petits cumulus bien séparés : lʼair est calme, le temps reste beau.', heart:'Une petite contrariété ressemble à ça : elle passe dans le ciel sans le couvrir.',
  svg:'<g fill="#fff"><ellipse cx="100" cy="92" rx="52" ry="16"/><ellipse cx="78" cy="78" rx="26" ry="20"/><ellipse cx="108" cy="68" rx="30" ry="26"/><ellipse cx="134" cy="82" rx="20" ry="15"/></g><rect x="50" y="94" width="100" height="14" fill="#fff"/>'},
 {id:'cb', n:'Le cumulonimbus', ty:'le grand nuage dʼorage', q:'Ce nuage monte très haut, avec une base sombre. Que va-t-il se passer ?', o:['Rien du tout','Une grosse averse, peut-être de lʼorage, puis ça se dégage','Du brouillard toute la journée'], ok:1, why:'Cʼest le géant du ciel : grosse averse, vent, parfois tonnerre. Sous les tropiques il se vide vite, et le soleil revient.', heart:'La colère lui ressemble : énorme, bruyante… et elle se vide. On attend à lʼabri quʼelle passe, on ne décide rien dessous.',
  svg:'<path d="M40 150 L44 86 Q20 80 30 62 Q34 46 56 50 Q60 22 96 26 Q104 6 132 12 Q170 10 178 30 Q150 34 150 50 Q176 58 164 80 Q160 92 150 92 L156 150Z" fill="#fff"/><path d="M40 150 L43 104 Q100 118 153 104 L156 150Z" fill="#6E7F8D"/><path d="M60 122 l-6 22 M84 124 l-6 22 M108 124 l-6 22 M132 122 l-6 22" stroke="#DDF1FA" stroke-width="2.4" stroke-linecap="round"/>'},
 {id:'cirrus', n:'Les cirrus', ty:'les cheveux du ciel, très haut', q:'Ces fins filaments blancs, tout là-haut, disent quoi ?', o:['Quʼil pleut déjà','Que le temps peut changer dans un jour ou deux','Quʼil va geler'], ok:1, why:'Les cirrus sont faits de glace, très haut. Ils arrivent souvent en avance sur un changement de temps.', heart:'Parfois on sent venir quelque chose avant de savoir quoi. Ce nʼest pas une tempête : cʼest un signe à écouter tranquillement.',
  svg:'<g fill="none" stroke="#fff" stroke-width="3.4" stroke-linecap="round" opacity=".95"><path d="M20 60 q40 -26 90 -14 q20 4 30 -8"/><path d="M50 96 q46 -24 100 -10 q16 4 26 -6"/><path d="M14 124 q30 -16 70 -8"/><path d="M96 36 q30 -14 70 -4"/></g>'},
 {id:'stratus', n:'Le stratus', ty:'le voile gris, bas et étalé', q:'Le ciel est gris partout, sans forme. Quʼest-ce que ça donne ?', o:['Un temps gris, parfois une pluie fine, sans orage','Un cyclone','Un grand soleil dans cinq minutes'], ok:0, why:'Le stratus est une couche basse : pas de violence, juste du gris, parfois de la bruine.', heart:'La tristesse fait souvent ça : pas dʼorage, juste du gris étalé. Au-dessus de la couche, le soleil nʼa pas bougé.',
  svg:'<rect x="0" y="0" width="200" height="150" fill="#B7C3CC"/><g fill="#9DAAB5"><rect x="0" y="34" width="200" height="16"/><rect x="0" y="76" width="200" height="12"/></g><g fill="#CFD8DE"><rect x="0" y="56" width="200" height="10"/><rect x="0" y="100" width="200" height="14"/></g><path d="M40 124 l-3 12 M80 126 l-3 12 M120 124 l-3 12 M160 126 l-3 12" stroke="#EEF4F7" stroke-width="1.6" stroke-linecap="round"/>'},
 {id:'mouʻa', n:'Le nuage de la montagne', ty:'celui qui sʼaccroche aux sommets', q:'Pourquoi un nuage coiffe-t-il souvent la montagne lʼaprès-midi ?', o:['La montagne fabrique de la fumée','Lʼair humide monte la pente, se refroidit, et devient nuage','Le nuage est coincé'], ok:1, why:'Le vent pousse lʼair de la mer contre lʼîle. En montant, il se refroidit et lʼeau quʼil porte devient nuage : cʼest pour ça quʼil pleut plus dans les vallées.', heart:'Certaines émotions reviennent toujours au même endroit, comme ce nuage. Le savoir, cʼest déjà pouvoir sʼy préparer.',
  svg:'<path d="M0 150 L52 70 L84 104 L118 40 L160 110 L200 86 L200 150Z" fill="#3B8C58"/><path d="M118 40 l-12 24 l12 -6 l10 8z" fill="#2A6B45"/><g fill="#fff"><ellipse cx="118" cy="44" rx="46" ry="14"/><ellipse cx="96" cy="36" rx="22" ry="14"/><ellipse cx="130" cy="30" rx="26" ry="16"/></g>'}];
const SKYW=[
 {id:'maraamu', n:'Maraʻamu', dir:'SE', x:80, y:84, d:'Lʼalizé du sud-est : frais, sec, souvent fort, surtout à la saison fraîche. La mer se creuse.', heart:'Ça souffle fort en toi : de lʼénergie, de lʼagitation.', tip:'Donne-lui une sortie : marcher, courir, nager, danser. Le vent fort a besoin dʼespace.'},
 {id:'toerau', n:'Toʻerau', dir:'N', x:50, y:7, d:'Le vent du nord : chaud, humide, lourd. Il amène souvent la pluie.', heart:'Cʼest lourd et chargé en toi, comme avant la pluie.', tip:'Ce qui est chargé a besoin de tomber : en parler à quelquʼun, écrire, ou respirer avec la vague.'},
 {id:'maoae', n:'Maoaʻe', dir:'E', x:90, y:40, d:'Lʼalizé dʼest : régulier et doux, le vent des beaux jours.', heart:'Cʼest régulier en toi : tu avances tranquille.', tip:'Remarque-le. Les jours calmes comptent aussi : pose un coquillage sur la plage.'},
 {id:'hupe', n:'Hupe', dir:'la montagne, la nuit', x:50, y:66, d:'La brise fraîche qui descend des vallées quand la nuit tombe.', heart:'Cʼest le soir en toi : tu as besoin de fraîcheur et de repos.', tip:'Ralentis. Bois de lʼeau, pose lʼécran un moment, dors si tu peux.'}];
function revaHead(t){ return `<div class="head"><div><div class="eyebrow">Te reva · le monde du ciel</div><h2>${t}</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div>`; }
function revaReward(key){ try{ const R=revaDone(); if(key && !R[key]){ R[key]=dayKey(Date.now()); store.set('reva',R); feathers+=5; store.set('feathers',feathers); renderFeathers(); const el=$('#dayScene'); if(el) el.dataset.p=''; renderPlace(); return true; }
    const k=dayKey(Date.now()); if(!key && store.get('revaDay','')!==k){ store.set('revaDay',k); feathers+=1; store.set('feathers',feathers); renderFeathers(); } }catch(e){} return false; }
function openReva(){ const R=revaDone(), kc=store.get('skyC',[]), kw=store.get('skyW',[]);
  openSheet(revaHead('Lire le ciel')+`<p>Le ciel change tout le temps, et il ne reste jamais bloqué. Ce qui se passe en toi, cʼest pareil : cʼest un temps quʼil fait, pas ce que tu es.</p>
    <div class="bkpick" style="display:grid;gap:10px"><button class="btn" id="rvC" style="display:block;width:100%;text-align:left;line-height:1.35"><b>Les nuages</b>${R.clouds?' ✓':''}<br><span class="small muted">${kc.length} sur ${SKYC.length} reconnus. Chacun annonce quelque chose.</span></button>
    <button class="btn" id="rvW" style="display:block;width:100%;text-align:left;line-height:1.35"><b>Les vents</b>${R.winds?' ✓':''}<br><span class="small muted">${kw.length} sur ${SKYW.length} connus. Et le vent qui souffle en toi aujourdʼhui.</span></button></div>
    <p class="small muted">Les noms tahitiens des vents sont en cours de vérification avec des locuteurs.</p>`);
  $('#sx').onclick=closeSheet; $('#rvC').onclick=()=>{ RV={k:'c', list:skyPick(SKYC,kc), i:0, pick:null}; revaCloud(); }; $('#rvW').onclick=()=>{ RV={k:'w', i:-1, pick:null, inner:null}; revaWind(); }; }
let RV={};
function skyPick(all,known){ const nw=all.filter(x=>!known.includes(x.id)), old=all.filter(x=>known.includes(x.id)).sort(()=>Math.random()-.5); return nw.concat(old).slice(0,3); }
function revaCloud(){ const c=RV.list[RV.i]; if(!c){ const kc=store.get('skyC',[]); const all=SKYC.every(x=>kc.includes(x.id)); const first=all && revaReward('clouds'); revaReward();
    openSheet(revaHead('Le ciel est lu')+`<p>${all?'Tu reconnais les cinq nuages.':'Tu reconnais '+kc.length+' nuages sur '+SKYC.length+'. Les autres viendront.'}</p>${first?'<div class="note">Un ānuanua, un arc-en-ciel, sʼest posé dans le ciel de Te reva. Il restera. (+5 plumes)</div>':''}<div class="note">Un nuage noir nʼest pas tout le ciel. Et aucun nuage ne reste.</div><button class="btn primary" id="rvEnd">Māuruuru</button>`);
    $('#sx').onclick=closeSheet; $('#rvEnd').onclick=()=>{ closeSheet(); say('Le ciel change. Toi aussi, et cʼest normal.'); }; return; }
  const done=RV.pick!==null;
  openSheet(revaHead(done?c.n:'Quel temps annonce-t-il ?')+`<div class="skyfig"><svg viewBox="0 0 200 150" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${esc(c.ty)}">${c.svg}</svg></div><p>${done?`<b>${c.n}</b>, ${c.ty}.`:c.q}</p><div class="stack" id="rvO">${c.o.map((t,i)=>`<button class="pans ${done&&i===c.ok?'good':done&&i===RV.pick?'meh':''}" data-v="${i}" ${done?'disabled':''}>${t}</button>`).join('')}</div>${done?`<div class="card flat"><p class="small">${c.why}</p></div><div class="note">${c.heart}</div><button class="btn primary" id="rvNext">${RV.i<RV.list.length-1?'Nuage suivant':'Terminer'}</button>`:''}`);
  sheetInner.scrollTop=done?sheetInner.scrollHeight:0; $('#sx').onclick=closeSheet;
  if(!done) $('#rvO').addEventListener('click', e=>{ const b=e.target.closest('[data-v]'); if(!b) return; RV.pick=+b.dataset.v; if(RV.pick===c.ok){ const kc=store.get('skyC',[]); if(!kc.includes(c.id)){ kc.push(c.id); store.set('skyC',kc); } } revaCloud(); });
  else $('#rvNext').onclick=()=>{ RV.i++; RV.pick=null; revaCloud(); }; }
function roseSVG(){ return `<svg viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="92" fill="#DDF1FA" stroke="#8CC6EE" stroke-width="2"/><path d="M100 14 L108 100 L100 186 L92 100Z" fill="#8CC6EE" opacity=".6"/><path d="M14 100 L100 92 L186 100 L100 108Z" fill="#8CC6EE" opacity=".6"/><ellipse cx="100" cy="100" rx="30" ry="20" fill="#7FD6DE"/><path d="M82 102 Q88 88 100 92 Q112 84 118 102 Q104 110 82 102Z" fill="#3B8C58"/><text x="100" y="50" text-anchor="middle" font-size="11" font-weight="700" fill="#16303B">N</text><text x="100" y="160" text-anchor="middle" font-size="11" font-weight="700" fill="#16303B">S</text><text x="150" y="104" text-anchor="middle" font-size="11" font-weight="700" fill="#16303B">E</text><text x="50" y="104" text-anchor="middle" font-size="11" font-weight="700" fill="#16303B">O</text></svg>`; }
function revaWind(){ const kw=store.get('skyW',[]);
  if(RV.i===-1){ openSheet(revaHead('Les vents de lʼîle')+`<p>Touche un vent pour le connaître. Lʼîle est au milieu : chaque vent vient dʼun côté.</p><div class="rose">${roseSVG()}${SKYW.map(w=>`<button data-w="${w.id}" class="${kw.includes(w.id)?'good':''}" style="left:${w.x}%;top:${w.y}%">${w.n}</button>`).join('')}</div><div id="rvInfo" aria-live="polite"><p class="small muted">${kw.length} sur ${SKYW.length} connus.</p></div><button class="btn primary" id="rvIn">Quel vent souffle en moi aujourdʼhui ?</button>`);
    $('#sx').onclick=closeSheet; sheetInner.querySelector('.rose').addEventListener('click', e=>{ const b=e.target.closest('[data-w]'); if(!b) return; const w=SKYW.find(x=>x.id===b.dataset.w); const k=store.get('skyW',[]); if(!k.includes(w.id)){ k.push(w.id); store.set('skyW',k); } sheetInner.querySelectorAll('.rose button').forEach(x=>x.classList.toggle('on',x===b)); b.classList.add('good'); $('#rvInfo').innerHTML=`<div class="card flat"><div class="eyebrow">${w.n} · vient de : ${w.dir}</div><p class="small">${w.d}</p></div>`; });
    $('#rvIn').onclick=()=>{ RV.i=0; revaWind(); }; return; }
  if(!RV.inner){ openSheet(revaHead('Le vent en moi')+`<p>Aucun vent nʼest mauvais : chacun dit de quoi tu as besoin. Lequel ressemble le plus à aujourdʼhui ?</p><div class="stack" id="rvO">${SKYW.map(w=>`<button class="pans" data-v="${w.id}"><b>${w.n}</b><span class="small">${w.heart}</span></button>`).join('')}</div>`);
    $('#sx').onclick=closeSheet; $('#rvO').addEventListener('click', e=>{ const b=e.target.closest('[data-v]'); if(!b) return; RV.inner=b.dataset.v; revaWind(); }); return; }
  const w=SKYW.find(x=>x.id===RV.inner), all=SKYW.every(x=>kw.includes(x.id)), first=all && revaReward('winds'); revaReward();
  openSheet(revaHead(w.n+' souffle en toi')+`<div class="card flat"><p>${w.heart}</p><p class="small">${w.tip}</p></div>${first?'<div class="note">Tu connais les quatre vents : un pāuma, un cerf-volant, vole maintenant dans le ciel de Te reva. (+5 plumes)</div>':''}<div class="note">Le vent tourne. Celui de ce soir ne sera pas celui de demain.</div>${w.id==='toerau'?'<button class="btn" id="rvBr">Respirer avec la vague</button>':''}<button class="btn primary" id="rvEnd">Māuruuru</button>`);
  $('#sx').onclick=closeSheet; $('#rvEnd').onclick=()=>{ closeSheet(); say('Merci de mʼavoir dit quel vent souffle. Je vole avec.'); }; if($('#rvBr')) $('#rvBr').onclick=()=>{ closeSheet(); openBreath(null); }; }
{ const _si=sceneInner; sceneInner=function(id){ return id==='reva' ? revaScene() : _si.apply(this,arguments); };
  const _pa=placeAct; placeAct=function(){ if(curPlace==='reva'){ openReva(); return; } return _pa.apply(this,arguments); };
  const _op=openPlace; openPlace=function(){ const r=_op.apply(this,arguments); try{ const got=stonesGot(), ks=Object.keys(STONE).filter(k=>got[k]); if(ks.length){ const c=document.createElement('div'); c.className='card flat'; c.innerHTML=`<div class="eyebrow">${store.get('portal',false)?'Les quatre pierres':'Pierres trouvées'}</div>${ks.map(k=>`<div class="stonerow">${stoneSVG(STONE[k].c)}<span class="small">${STONE[k].n.charAt(0).toUpperCase()+STONE[k].n.slice(1)}</span></div>`).join('')}<p class="small muted">${store.get('portal',false)?'Ensemble, elles ont ouvert le passage vers Te reva.':'Personne ne sait encore à quoi elles servent.'}</p>`; sheetInner.appendChild(c); } }catch(e){} return r; };
  const _cs3=closeSheet; closeSheet=function(){ const r=_cs3.apply(this,arguments); setTimeout(stoneTick,1200); return r; }; }
setTimeout(()=>{ try{ if(typeof QI!=='undefined'){ QI.reva='<rect x="2" y="2" width="24" height="24" rx="7" fill="#8CC6EE"/><circle cx="19" cy="9" r="4" fill="#FFE08A"/><g fill="#fff"><ellipse cx="12" cy="19" rx="9" ry="4"/><ellipse cx="9" cy="15.5" rx="4.5" ry="3.6"/><ellipse cx="14.5" cy="14" rx="5" ry="4.4"/></g>'; QI.nuage='<g fill="#fff" stroke="#8FB7B7" stroke-width="1.2"><path d="M7 21 q-5 0 -4 -5 q1 -4 5 -3 q1 -6 7 -5 q5 1 5 6 q5 0 4 4 q-1 3 -4 3z"/></g>'; QI.vent='<g fill="none" stroke="#2F8FB0" stroke-width="2.2" stroke-linecap="round"><path d="M3 10 h13 q4 0 4 -3 q0 -3 -3 -3"/><path d="M3 15 h18 q4 0 4 3 q0 3 -3 3"/><path d="M3 20 h9"/></g>'; QPL.reva='Ciel';
      const _qa=qActs; qActs=function(){ return curPlace==='reva' ? [{k:'nuage',l:'Nuages',t:'Les nuages',go:()=>{ RV={k:'c', list:skyPick(SKYC,store.get('skyC',[])), i:0, pick:null}; revaCloud(); }},{k:'vent',l:'Vents',t:'Les vents',go:()=>{ RV={k:'w', i:-1, pick:null, inner:null}; revaWind(); }}] : _qa.apply(this,arguments); }; dockRender(); } }catch(e){}
  try{ if(/[?&]ciel=1/.test(location.search) && !store.get('portal',false)){ const g={}; Object.keys(STONE).forEach(k=>g[k]=dayKey(Date.now())); store.set('stones',g); } }catch(e){}
  try{ if(curPlace==='reva'){ const el=$('#dayScene'); if(el) el.dataset.p=''; renderPlace(); } }catch(e){}
  stoneTick(); },50);
setInterval(stoneTick,20000);

"""
    rep("/* ---------- install button ---------- */", new+"/* ---------- install button ---------- */")
    open(path,'w',encoding='utf8').write(s)
    print('ok',path)
