# Patch "lʼatelier des instruments : ukulele, tōʻere, pahu — fabriqués avec les récoltes, décorés, et la musique qui fait pousser le faʻaʻapu".
# Base v91 (le faʻaʻapu, le coffre, le synthé du ukulele). Usage : python3 instr_patch.py <site>/index.html <manu-ora.html>
import sys
for path in sys.argv[1:]:
    s=open(path,encoding='utf8').read()
    def rep(a,b,n=1):
        global s
        assert s.count(a)==n,(path,a[:70],s.count(a))
        s=s.replace(a,b)
    rep(".pepes{position:absolute;",""".insfig{flex:none;height:150px;border-radius:16px;background:linear-gradient(#FFF6E3,#F1DDB0);margin:8px 0;overflow:hidden}.insfig svg{width:100%;height:100%;display:block}
.inscost{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}.inscost span{border:1.5px solid var(--line);border-radius:999px;padding:3px 10px;font-size:.85rem;font-weight:700}.inscost span.ok{border-color:var(--fern)}.inscost span.no{opacity:.6}
.insplay{animation:insPlay .5s ease-in-out 3}@keyframes insPlay{50%{transform:translateY(-4px) rotate(-2deg)}}
@media (prefers-reduced-motion:reduce){.insplay{animation:none}}
.pepes{position:absolute;""")
    new = r"""/* ---------- lʼatelier des instruments : fabriquer, décorer, jouer pour le faʻaʻapu ---------- */
const INS_FLOWER=['tiare','aute','tipanie','vanira','apetahi','autex','tipax','ahia'], INS_FRUIT=['meia','vi','painapo','anani','iita','nono','vix','taro'], INS_TREE=['haari','uru','tou','tamanu','fara','tiairi','mati'];
const INS={
  uke:{n:'Le ʻukulele', s:'taillé dans une seule pièce de bois, huit cordes', need:{bois:2}, plumes:5, plumesWhy:'le fil de pêche des cordes, au marché', grows:INS_FLOWER, gw:'les fleurs', say:'Les fleurs aiment les cordes : elles sʼouvrent un peu plus vite.'},
  toere:{n:'Le tōʻere', s:'un tronc creusé, fendu sur le dessus, quʼon frappe avec deux baguettes', need:{bois:3}, plumes:0, grows:INS_TREE, gw:'les arbres', say:'Le tōʻere réveille les troncs : les arbres poussent un peu plus vite.'},
  pahu:{n:'Le pahu', s:'le grand tambour, un tronc creusé et une peau tendue, lacée avec la bourre de coco', need:{bois:2, haari:2}, plumes:5, plumesWhy:'la peau, préparée par un artisan', grows:INS_FRUIT, gw:'les fruits', say:'Le pahu fait battre le cœur du faʻaʻapu : les fruits mûrissent un peu plus vite.'}};
const INS_FIN={ nat:{n:'Naturel', s:'le bois tel quel', h:6, cost:null}, grav:{n:'Gravé', s:'des motifs de tatau gravés dans le bois', h:9, cost:{plumes:3}}, nacre:{n:'Nacré', s:'incrusté dʼune perle de nacre', h:12, cost:{poe:1}} };
function insGet(){ const o=store.get('instr',null); return (o && typeof o==='object') ? o : {}; }
function insWood(){ return (garden.store.tou||0)+(garden.store.uru||0); }
function insHave(k,n){ if(k==='bois') return insWood()>=n; if(k==='plumes') return feathers>=n; return (garden.store[k]||0)>=n; }
function insTake(k,n){ if(k==='bois'){ for(let i=0;i<n;i++){ if((garden.store.tou||0)>0) garden.store.tou--; else garden.store.uru--; } return; } if(k==='plumes'){ feathers-=n; store.set('feathers',feathers); renderFeathers(); return; } garden.store[k]-=n; }
const insLbl=k=>k==='bois'?'bois (tou ou ʻuru)':k==='haari'?'coco (pour la bourre)':k==='poe'?'perle':k==='plumes'?'plumes':((PLANTS[k]&&PLANTS[k].name)||k);
function insSVG(id,fin){ const wood = fin==='nacre' ? '#8A5A2B' : '#A8743A', dark='#5C3A1E';
  const tat = fin==='grav'||fin==='nacre' ? (id==='uke' ? `<path d="M118 70 l8 -8 l8 8 l8 -8 l8 8 M118 92 l8 -8 l8 8 l8 -8 l8 8" stroke="${dark}" stroke-width="1.6" fill="none"/>` : id==='toere' ? `<path d="M70 108 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10" stroke="${dark}" stroke-width="1.6" fill="none"/>` : `<path d="M120 70 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10 M120 116 l10 -10 l10 10 l10 -10 l10 10 l10 -10 l10 10" stroke="${dark}" stroke-width="1.6" fill="none"/>`) : '';
  const nac = fin==='nacre' ? (id==='uke' ? `<circle cx="140" cy="80" r="7" fill="#DCE6EA" stroke="#9FB3BC"/><circle cx="138" cy="78" r="2" fill="#fff"/>` : id==='toere' ? `<circle cx="160" cy="98" r="6" fill="#DCE6EA" stroke="#9FB3BC"/><circle cx="200" cy="98" r="6" fill="#DCE6EA" stroke="#9FB3BC"/>` : `<circle cx="160" cy="92" r="7" fill="#DCE6EA" stroke="#9FB3BC"/>`) : '';
  if(id==='uke') return `<svg viewBox="0 0 320 150" role="img" aria-label="Un ʻukulele"><g transform="rotate(-12 160 80)"><rect x="168" y="70" width="110" height="16" rx="4" fill="${wood}" stroke="${dark}" stroke-width="1.6"/><path d="M276 66 h22 q6 0 6 6 v12 q0 6 -6 6 h-22z" fill="${wood}" stroke="${dark}" stroke-width="1.6"/>${[0,1,2,3].map(i=>`<circle cx="${284+i*0}" cy="${70+i*4}" r="1.6" fill="#F2C94C"/>`).join('')}<path d="M70 78 q0 -42 50 -42 q34 0 48 34 v16 q-14 34 -48 34 q-50 0 -50 -42z" fill="${wood}" stroke="${dark}" stroke-width="2"/><circle cx="120" cy="78" r="18" fill="#F1DDB0" stroke="${dark}" stroke-width="1.6"/>${tat}${nac}<rect x="92" y="72" width="8" height="12" rx="2" fill="${dark}"/>${[0,1,2,3].map(i=>`<path d="M96 ${73.5+i*3} H290" stroke="#3B8C58" stroke-width=".9"/>`).join('')}</g></svg>`;
  if(id==='toere') return `<svg viewBox="0 0 320 150" role="img" aria-label="Un tōʻere"><ellipse cx="160" cy="128" rx="120" ry="8" fill="#5C3A1E" opacity=".2"/><path d="M50 72 q0 -16 18 -16 h184 q18 0 18 16 v36 q0 16 -18 16 h-184 q-18 0 -18 -16z" fill="${wood}" stroke="${dark}" stroke-width="2"/><ellipse cx="60" cy="90" rx="10" ry="32" fill="#C99A5B" stroke="${dark}" stroke-width="1.4"/><path d="M80 66 h170" stroke="${dark}" stroke-width="5" stroke-linecap="round"/>${tat}${nac}<path d="M200 30 l40 26 M240 22 l30 34" stroke="#8A5A2B" stroke-width="5" stroke-linecap="round"/></svg>`;
  return `<svg viewBox="0 0 320 150" role="img" aria-label="Un pahu"><ellipse cx="160" cy="140" rx="60" ry="6" fill="#5C3A1E" opacity=".2"/><path d="M110 40 h100 l-10 98 h-80z" fill="${wood}" stroke="${dark}" stroke-width="2"/><ellipse cx="160" cy="40" rx="50" ry="10" fill="#F1E2C0" stroke="${dark}" stroke-width="1.6"/><g stroke="#8A6A3B" stroke-width="1.4">${Array.from({length:9},(_,i)=>`<path d="M${114+i*11} 46 L${124+i*8} 120"/>`).join('')}</g><path d="M120 120 h80" stroke="#8A6A3B" stroke-width="3"/>${tat}${nac}</svg>`; }
function insHead(t){ return `<div class="head"><div><div class="eyebrow">Le faʻaʻapu · lʼatelier des instruments</div><h2>${t}</h2></div><button class="x" id="sx" aria-label="Fermer">×</button></div>`; }
function insCost(need,pl){ const all=Object.assign({},need||{}); if(pl) all.plumes=pl; return Object.keys(all).map(k=>`<span class="${insHave(k,all[k])?'ok':'no'}">${insLbl(k)} : ${k==='bois'?Math.min(insWood(),all[k]):k==='plumes'?Math.min(feathers,all[k]):Math.min(garden.store[k]||0,all[k])} / ${all[k]}</span>`).join(''); }
function insCan(need,pl){ const all=Object.assign({},need||{}); if(pl) all.plumes=pl; return Object.keys(all).every(k=>insHave(k,all[k])); }
function openInstr(){ const O=insGet(), today=dayKey(Date.now());
  openSheet(insHead('Lʼatelier des instruments')+`<p>Avec ce que ton faʻaʻapu donne, on fabrique des instruments. Et quand on en joue au faʻaʻapu, les plantes aiment ça : chaque instrument fait pousser un peu plus vite une famille de plantes.</p><div class="note">La musique du faʻaʻapu, cʼest <b>une fois par jour</b>, avec un seul instrument : choisis bien lequel.${insToday()?' Aujourdʼhui, cʼest déjà fait : à demain !':''}</div>
    <div class="stack">${Object.keys(INS).map(id=>{ const I=INS[id], o=O[id]; return `<div class="card flat"><div class="insfig">${insSVG(id,o?o.fin:'nat')}</div><h3>${I.n}${o?' ✓':''}</h3><p class="small muted">${I.s}. Fait pousser ${I.gw}.</p>
      ${o?`<div class="row"><button class="btn sm primary" data-play="${id}" ${insToday()?'disabled':''}>${o.day===today?'Joué aujourdʼhui':insToday()?'Demain':'Jouer pour le faʻaʻapu'}</button><button class="btn sm" data-fin="${id}">Décorer · ${INS_FIN[o.fin||'nat'].n}</button></div>`:`<div class="inscost">${insCost(I.need,I.plumes)}</div>${I.plumesWhy?`<p class="small muted">Les plumes : ${I.plumesWhy}.</p>`:''}<button class="btn sm ${insCan(I.need,I.plumes)?'primary':''}" data-make="${id}">Fabriquer</button>`}</div>`; }).join('')}</div>
    <p class="small muted">Le bois vient du tou et de lʼʻuru, la bourre du coco : plante des arbres dans ton faʻaʻapu.</p>`);
  $('#sx').onclick=closeSheet;
  sheetInner.querySelectorAll('[data-make]').forEach(b=>b.onclick=()=>insMake(b.dataset.make));
  sheetInner.querySelectorAll('[data-fin]').forEach(b=>b.onclick=()=>insFinish(b.dataset.fin));
  sheetInner.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>insPlay(b.dataset.play)); }
function insMake(id){ const I=INS[id]; if(!insCan(I.need,I.plumes)){ const miss=Object.keys(Object.assign({},I.need,I.plumes?{plumes:I.plumes}:{})).filter(k=>!insHave(k,(I.need[k]||I.plumes))).map(insLbl).join(', '); toast('Il manque : '+miss); return; }
  Object.keys(I.need).forEach(k=>insTake(k,I.need[k])); if(I.plumes) insTake('plumes',I.plumes); saveGarden(); const O=insGet(); O[id]={fin:'nat', day:''}; store.set('instr',O);
  openSheet(insHead(I.n+' est prêt')+`<div class="insfig">${insSVG(id,'nat')}</div><p>${id==='uke'?'On a creusé, poncé, tendu les huit cordes. Il sonne.':id==='toere'?'On a creusé le tronc et ouvert la fente. Il claque.':'On a creusé le tronc, tendu la peau, lacé la bourre de coco. Il gronde.'}</p><div class="note">Ce qui prend du temps à fabriquer, on en prend soin.</div><button class="btn primary" id="insBack">Retour à lʼatelier</button>`); $('#sx').onclick=closeSheet; $('#insBack').onclick=openInstr; }
function insFinish(id){ const O=insGet(), o=O[id]; if(!o) return;
  openSheet(insHead('Décorer '+INS[id].n.replace(/^Le /,'le '))+`<div class="insfig" id="insPrev">${insSVG(id,o.fin||'nat')}</div><p class="small muted">Une décoration plus travaillée rend la musique plus forte pour le faʻaʻapu.</p><div class="stack">${Object.keys(INS_FIN).map(f=>{ const F=INS_FIN[f], on=(o.fin||'nat')===f, owned=(o.owned||['nat']).includes(f); return `<button class="pans ${on?'good':''}" data-f="${f}"><b>${F.n}${on?' ✓':''}</b><span class="small">${F.s} · ${F.h} h de pousse en plus${!owned&&F.cost?` · ${F.cost.plumes?F.cost.plumes+' plumes':'1 perle du coffre'}`:''}</span></button>`; }).join('')}</div><button class="btn ghost" id="insBack">Retour</button>`);
  $('#sx').onclick=closeSheet; $('#insBack').onclick=openInstr;
  sheetInner.querySelectorAll('[data-f]').forEach(b=>{ b.onmouseenter=()=>{ $('#insPrev').innerHTML=insSVG(id,b.dataset.f); }; b.onclick=()=>{ const f=b.dataset.f, F=INS_FIN[f], O2=insGet(), o2=O2[id]; o2.owned=o2.owned||['nat'];
    if(!o2.owned.includes(f) && F.cost){ if(F.cost.plumes){ if(feathers<F.cost.plumes){ toast('Il manque des plumes'); return; } insTake('plumes',F.cost.plumes); } if(F.cost.poe){ if((garden.store.poe||0)<1){ toast('Il faut une perle : on en trouve parfois sur la plage'); return; } garden.store.poe--; saveGarden(); } o2.owned.push(f); }
    o2.fin=f; store.set('instr',O2); toast(INS[id].n+' : '+F.n.toLowerCase()); insFinish(id); }; }); }
function insSound(id){ try{ AC = AC || new (window.AudioContext||window.webkitAudioContext)(); if(AC.state!=='running') AC.resume(); }catch(e){ return; }
  try{ if(id==='uke'){ if(!UKE.on) playUke(store.get('ukeTune','matamua'),{after:()=>{}}); return; } const t0=AC.currentTime+.08; if(id==='toere'){ [0,.16,.32,.4,.56,.72,.8,.96,1.12,1.2,1.36,1.52].forEach((d,i)=>drumHit(t0+d,i%3===2?'lo':'hi')); } else { [0,.5,.75,1.25,1.5,2].forEach(d=>drumHit(t0+d,'pahu')); } }catch(e){} }
function insToday(){ const O=insGet(), k=dayKey(Date.now()); return Object.keys(O).some(i=>O[i] && O[i].day===k); }
function insPlay(id){ const O=insGet(), o=O[id], today=dayKey(Date.now()); if(!o || insToday()) return; const I=INS[id], h=INS_FIN[o.fin||'nat'].h; let n=0;
  garden.plots.forEach(pl=>{ if(pl && I.grows.includes(pl.p) && plotStage(pl)<3){ pl.t-=h*36e5; n++; } }); o.day=today; store.set('instr',O); saveGarden(); insSound(id);
  openSheet(insHead('On joue pour le faʻaʻapu')+`<div class="insfig insplay">${insSVG(id,o.fin||'nat')}</div><p>${n?I.say:`Aucune plante de cette famille ne pousse en ce moment : ${I.gw}, ce sera pour une prochaine fois. La musique, elle, a fait du bien quand même.`}</p>${n?`<div class="note">${n} plante${n>1?'s':''} : ${h} h de pousse en plus.</div>`:''}<button class="btn primary" id="insG">Voir le faʻaʻapu</button><button class="btn ghost" id="insBack">Retour à lʼatelier</button>`);
  $('#sx').onclick=closeSheet; $('#insBack').onclick=openInstr; $('#insG').onclick=()=>openGarden(); if(!RM) for(let i=0;i<8;i++) setTimeout(()=>petal(B.x+BW/2+(Math.random()*80-40),B.y+10),i*160); }
{ const _og=openGarden; openGarden=function(){ const r=_og.apply(this,arguments); try{ const c=document.createElement('div'); c.className='card flat'; const O=insGet(), made=Object.keys(O).length; c.innerHTML=`<div class="eyebrow">Lʼatelier des instruments</div><p class="small muted">${made?`${made} instrument${made>1?'s':''} fabriqué${made>1?'s':''}. Jouer au faʻaʻapu fait pousser les plantes.`:'Avec le bois et la bourre de coco du faʻaʻapu, fabrique un ʻukulele, un tōʻere ou un pahu.'}</p><button class="btn sm" id="insOpen">Ouvrir lʼatelier</button>`; sheetInner.appendChild(c); $('#insOpen').onclick=openInstr; }catch(e){} return r; }; }

"""
    rep("/* ---------- install button ---------- */", new+"/* ---------- install button ---------- */")
    open(path,'w',encoding='utf8').write(s)
    print('ok',path)
