# Patch "Te reva, suite et fin : l'île vue d'en haut, le fare (avec l'aide d'un cœur lié), le grand vol (rétrospective + constellation)".
# Dépend de sky-patch (donc de scene-patch). Usage : python3 voyage_patch.py <site>/index.html <manu-ora.html>
import sys
for path in sys.argv[1:]:
    s=open(path,encoding='utf8').read()
    def rep(a,b,n=1):
        global s
        assert s.count(a)==n,(path,a[:70],s.count(a))
        s=s.replace(a,b)
    assert 'function openReva()' in s, 'appliquer sky-patch avant'
    rep("    else if(v.g==='pardon'){ for(let i=0;i<6;i++)","    else if(v.g==='fareAsk'){ setTimeout(()=>fareInvite(v),9200); }\n    else if(v.g==='fareAid'){ fareAided(v); for(let i=0;i<6;i++) setTimeout(()=>petal(mx+(Math.random()*60-30),my-10),i*200); }\n    else if(v.g==='pardon'){ for(let i=0;i<6;i++)")
    rep("if(m.indexOf('love:')===0){ loveBtn(m.slice(5)); return; }","if(m.indexOf('vy:')===0){ vyBtn(m.split(':')); return; } if(m.indexOf('love:')===0){ loveBtn(m.slice(5)); return; }")
    # entrées dans le menu de Te reva
    rep("""<p class="small muted">Les noms tahitiens des vents sont en cours de vérification avec des locuteurs.</p>`);
  $('#sx').onclick=closeSheet; $('#rvC').onclick=""","""${revaMore()}<p class="small muted">Les noms tahitiens des vents sont en cours de vérification avec des locuteurs.</p>`);
  revaMoreWire(); $('#sx').onclick=closeSheet; $('#rvC').onclick=""")
    rep(".pepes{position:absolute;",""".imap{flex:none;position:relative;width:min(100%,320px);aspect-ratio:1;margin:8px auto}.imap svg{width:100%;height:100%;border-radius:18px}
.imap button{position:absolute;transform:translate(-50%,-50%);border:1.5px solid var(--line);background:rgba(255,255,255,.94);border-radius:999px;padding:4px 9px;font-family:var(--display);font-weight:700;font-size:.74rem;color:#16303B}
.imap button.on{border-color:var(--lagoon);background:#E3F2F1}.imap button.good{border-color:var(--fern)}
.farefig{flex:none;height:170px;border-radius:16px;overflow:hidden;background:linear-gradient(#BEE5F6 0%,#F7FBF0 66%,#CFE3A8 66%,#B5D48A 100%);margin:8px 0}.farefig svg{width:100%;height:100%;display:block}
.retro{flex:none;display:flex;flex-wrap:wrap;gap:3px;margin:8px 0}.retro span{width:14px;height:14px;border-radius:4px}
.retrow{display:flex;gap:8px;justify-content:space-around;align-items:flex-end;margin:8px 0}.retrow div{width:30%;text-align:center;font-size:.72rem;font-weight:700}
.chips{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}.chips span{border:1.5px solid var(--line);border-radius:999px;padding:3px 9px;font-size:.82rem;font-weight:700}
.cstfx{position:fixed;inset:0;z-index:9000;background:linear-gradient(#0B1533,#1B2A5C);opacity:0;transition:opacity 1s;display:grid;place-items:center;overflow:hidden}.cstfx.on{opacity:1}
.cstfx svg{width:min(92vw,420px);height:auto;overflow:visible}
.cstfx .cb{transform-box:fill-box;transform-origin:center;animation:cstUp 4.2s ease-in both}
.cstfx .cs{opacity:0;animation:cstStar .9s ease-out forwards}.cstfx .cl{opacity:0;animation:cstStar 1.4s 6.6s ease-out forwards}.cstfx .ct{opacity:0;animation:cstStar 1.2s 7.6s ease-out forwards;fill:#fff;font-family:var(--display);text-anchor:middle}
@keyframes cstUp{from{transform:translateY(190px) scale(1);opacity:1}75%{opacity:1}to{transform:translateY(0) scale(.5);opacity:0}}
@keyframes cstStar{to{opacity:1}}
@media (prefers-reduced-motion:reduce){.cstfx .cb{animation:none;opacity:0}.cstfx .cs,.cstfx .cl,.cstfx .ct{animation:none;opacity:1}}
.callmanu{position:absolute;right:14px;bottom:calc(36px + env(safe-area-inset-bottom,0px));z-index:3}
body.manu-up #bird{visibility:hidden}
.retrow .uke,.cstfx .uke{display:none}
.pepes{position:absolute;""")
    new = r"""/* ---------- Te reva, suite : lʼîle vue dʼen haut, le fare, le grand vol ---------- */
const ISL=[
 {id:'moua', n:'Mouʻa', fr:'la montagne', x:50, y:46, d:'Le sommet arrête les nuages : cʼest lui qui fait tomber la pluie et naître les rivières.', h:'Ce qui est solide en toi fait la même chose : ça transforme le mauvais temps en quelque chose qui nourrit.'},
 {id:'faa', n:'Faʻa', fr:'la vallée', x:36, y:60, d:'Lʼeau descend par les vallées jusquʼà la mer. Tout y pousse.', h:'Ce que tu ressens a besoin dʼun chemin pour descendre : parler, écrire, bouger.'},
 {id:'tahatai', n:'Tahatai', fr:'le rivage', x:66, y:66, d:'La bande de terre plate entre la montagne et le lagon : cʼest là que vivent presque tous les gens.', h:'On vit au bord : entre ce qui est solide et ce qui bouge.'},
 {id:'tairoto', n:'Tairoto', fr:'le lagon', x:24, y:38, d:'Lʼeau calme et claire entre lʼîle et le récif.', h:'Ton calme intérieur existe parce que quelque chose le protège.'},
 {id:'aau', n:'Aʻau', fr:'le récif', x:80, y:24, d:'La barrière de corail casse la houle du large. Sans lui, pas de lagon.', h:'Tes limites sont ton récif : dire non protège ton calme.'},
 {id:'ava', n:'Ava', fr:'la passe', x:14, y:66, d:'Lʼouverture dans le récif, souvent en face dʼune rivière : par là entrent et sortent les pirogues et les poissons.', h:'Un récif sans passe étouffe le lagon. Garde toujours une ouverture pour les autres.'},
 {id:'motu', n:'Motu', fr:'lʼîlot', x:84, y:76, d:'Un petit îlot de sable et de corail posé sur le récif.', h:'On a tous besoin dʼun petit coin à soi, pas trop loin des autres.'},
 {id:'moana', n:'Moana', fr:'lʼocéan', x:50, y:93, d:'Le grand large, au-delà du récif. Les anciens le traversaient en lisant les étoiles, les vents et les nuages.', h:'Cʼest le vrai monde : grand, pas toujours calme. On sʼy prépare, et on y va.'}];
const FARE_ST=[
 {n:'Les poteaux', ty:'te pou', need:{uru:2}, d:'On plante les poteaux. Ceux qui les portent ont faim : apporte deux ʻuru pour le repas du chantier.', h:'Un fare commence par ce qui ne se voit plus à la fin. Tes bases aussi.'},
 {n:'La charpente', ty:'te tahuhu', need:{haari:2}, d:'On attache les pièces avec de la corde de bourre de coco, sans un clou. Il faut deux cocos.', h:'Ce qui tient un fare, ce sont les liens. Toi aussi.'},
 {n:'Le toit', ty:'te tāpoʻi', need:{fara:3}, d:'On couvre avec des feuilles de pandanus cousues. Il en faut trois récoltes.', h:'Un toit ne supprime pas la pluie : il te laisse au sec pendant quʼelle tombe.'},
 {n:'La natte et lʼaccueil', ty:'te peʻue', need:{fara:1,tiare:1}, d:'Une natte tressée au sol et une fleur à lʼentrée : le fare est prêt à recevoir.', h:'Un lieu sûr, cʼest un lieu où lʼon peut entrer comme on est.'}];
function fareGet(){ const o=store.get('fare',null); return (o && typeof o==='object') ? o : {n:0, day:'', help:[], gift:0}; }
function fareSVG(n){ const g=n>=4?'#C9A24A':'#D9BE7A';
  return `<svg viewBox="0 0 320 170" preserveAspectRatio="xMidYMax meet" role="img" aria-label="Le fare, étape ${n} sur 4">${n>=1?'<g stroke="#8A5A2B" stroke-width="7" stroke-linecap="round"><path d="M100 150 V84"/><path d="M220 150 V84"/><path d="M140 150 V84"/><path d="M180 150 V84"/></g>':'<g fill="none" stroke="#8A5A2B" stroke-width="2" stroke-dasharray="5 5" opacity=".5"><rect x="96" y="84" width="128" height="66"/><path d="M84 86 L160 34 L236 86"/></g>'}
    ${n>=2?'<g stroke="#A8743A" stroke-width="5" stroke-linecap="round" fill="none"><path d="M88 86 H232"/><path d="M88 86 L160 36 L232 86"/><path d="M124 62 H196"/><path d="M160 36 V86"/></g><g fill="#F1DDB0"><circle cx="100" cy="86" r="4"/><circle cx="220" cy="86" r="4"/><circle cx="160" cy="38" r="4"/></g>':''}
    ${n>=3?`<path d="M78 90 L160 28 L242 90 Z" fill="${g}" stroke="#8A6A2B" stroke-width="2" stroke-linejoin="round"/><g stroke="#8A6A2B" stroke-width="1.2" opacity=".7"><path d="M98 76 H222 M114 62 H206 M130 50 H190 M146 38 H174"/><path d="M110 90 V70 M130 90 V56 M150 90 V40 M170 90 V40 M190 90 V56 M210 90 V70"/></g>`:''}
    ${n>=4?'<rect x="104" y="92" width="112" height="56" fill="#E9D3A0" opacity=".9"/><g stroke="#C9A24A" stroke-width="1.2"><path d="M104 104 H216 M104 118 H216 M104 132 H216"/></g><rect x="146" y="104" width="28" height="44" fill="#6B4A2A"/><path d="M96 150 H224" stroke="#C9A24A" stroke-width="5"/><g transform="translate(160 98)"><circle r="3" fill="#F2C94C"/><g fill="#FFF9EE" stroke="#E8D9B5" stroke-width=".6"><circle cx="0" cy="-6" r="3.4"/><circle cx="5.7" cy="-1.9" r="3.4"/><circle cx="3.5" cy="4.9" r="3.4"/><circle cx="-3.5" cy="4.9" r="3.4"/><circle cx="-5.7" cy="-1.9" r="3.4"/></g></g>':''}</svg>`; }
function fareStage(){ const F=fareGet(), st=FARE_ST[F.n]; if(!st) return null; const have=k=>(garden.store[k]||0); const ok=Object.keys(st.need).every(k=>have(k)>=st.need[k]); return {F, st, ok, have}; }
function openFare(){ const F=fareGet(), S=fareStage(), today=dayKey(Date.now()), mut=(SYNC_URL?friends.filter(f=>isMutual(f.code)):[]);
  let h=revaHead(F.n>=4?'Te fare':'Bâtir un fare')+`<div class="farefig">${fareSVG(F.n)}</div>`;
  if(F.n>=4) h+=`<p>Ton fare est debout. Cʼest un lieu sûr : on y entre comme on est.</p>${F.help.length?`<div class="note">Bâti avec ${F.help.map(esc).join(', ')}. Un fare ne se monte jamais seul.</div>`:''}<button class="btn primary" id="frEnd">Māuruuru</button>`;
  else { const st=S.st, waits=F.day===today;
    h+=`<div class="eyebrow">Étape ${F.n+1} sur 4 · ${st.ty}</div><h3>${st.n}</h3><p class="small">${st.d}</p><div class="chips">${Object.keys(st.need).map(k=>`<span style="${S.have(k)>=st.need[k]||F.gift?'border-color:var(--fern)':''}">${PLANTS[k]?PLANTS[k].name:k} : ${F.gift?'offert':Math.min(S.have(k),st.need[k])+' / '+st.need[k]}</span>`).join('')}</div>`
     +(F.gift?`<div class="note">Un cœur lié est venu aider : cette étape est offerte.</div>`:'')
     +(waits?`<p class="small muted">Une étape par jour : le fare se bâtit sans se presser. Reviens demain.</p>`:`<button class="btn primary" id="frGo" ${(S.ok||F.gift)?'':'disabled style="opacity:.55"'}>Poser cette étape</button>${(S.ok||F.gift)?'':'<p class="small muted">Il manque des récoltes : elles poussent dans ton faʻaʻapu.</p>'}`)
     +(mut.length && !F.gift?`<div class="card flat"><div class="eyebrow">Demander un coup de main</div><p class="small muted">Un cœur lié peut venir aider : lʼétape suivante sera offerte.</p><div class="row" id="frFr">${mut.map(f=>`<button class="btn sm" data-f="${f.code}">${esc(f.name||fmtCode(f.code))}</button>`).join('')}</div></div>`:'')
     +(F.help.length?`<p class="small muted">Déjà venus aider : ${F.help.map(esc).join(', ')}.</p>`:''); }
  openSheet(h); $('#sx').onclick=closeSheet; if($('#frEnd')) $('#frEnd').onclick=closeSheet;
  if($('#frGo')) $('#frGo').onclick=()=>{ const S2=fareStage(); if(!S2 || !(S2.ok||S2.F.gift)) return; const F2=S2.F; if(F2.gift) F2.gift=0; else { Object.keys(S2.st.need).forEach(k=>{ garden.store[k]-=S2.st.need[k]; }); saveGarden(); } F2.n++; F2.day=dayKey(Date.now()); store.set('fare',F2); const el=$('#dayScene'); if(el) el.dataset.p=''; renderPlace();
    openSheet(revaHead(S2.st.n+' : posé')+`<div class="farefig">${fareSVG(F2.n)}</div><div class="note">${S2.st.h}</div><button class="btn primary" id="frOk">${F2.n>=4?'Le fare est fini':'À demain pour la suite'}</button>`); $('#sx').onclick=closeSheet; $('#frOk').onclick=()=>{ closeSheet(); if(F2.n>=4){ feathers+=10; store.set('feathers',feathers); renderFeathers(); say('Notre fare est debout. On peut y revenir par tous les temps. (+10 plumes)'); } }; };
  const fr=$('#frFr'); if(fr) fr.addEventListener('click', e=>{ const b=e.target.closest('[data-f]'); if(!b) return; const code=b.dataset.f, f=friends.find(x=>x.code===code), nm=f?(f.name||fmtCode(code)):''; fetch(`${SYNC_URL}/visits/${code}/${myCode}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({g:'fareAsk', t:Date.now(), name:share.name||''})}).then(r=>{ if(!r.ok){ toast('Envoi impossible, réessaie plus tard'); return; } const o=store.get('fareOut',{})||{}; o[code]=Date.now(); store.set('fareOut',o); closeSheet(); toast('Demande envoyée'); say('Je vais demander à '+nm+' !'); setTimeout(()=>flyAway(nm),1200); }).catch(()=>toast('Pas de connexion, réessaie plus tard')); }); }
GEST.fareAsk={l:'', t:'bâtit quelque chose et te demande un coup de main.'}; GEST.fareAid={l:'', t:'est venu·e aider à bâtir ton fare !'};
function fareInvite(v){ if(!visitFree() || bubbleEl.classList.contains('show')){ setTimeout(()=>fareInvite(v),5000); return; } sayHTML(`${esc(v.name)} bâtit quelque chose et aurait besoin de bras. On y va ?<div class="mini"><button data-m="vy:aid:${v.from}">Aller aider</button><button data-m="vy:no">Plus tard</button></div>`, 40000); }
function fareAided(v){ try{ const o=store.get('fareOut',{})||{}; if(!o[v.from]) return; delete o[v.from]; store.set('fareOut',o); const F=fareGet(); if(F.n>=4) return; F.gift=1; const nm=String(v.name||'').slice(0,12); if(nm && !F.help.includes(nm)) F.help.push(nm); F.help=F.help.slice(-8); store.set('fare',F); }catch(e){} }
function vyBtn(a){ bubbleEl.classList.remove('show'); if(a[1]==='aid'){ const f=friends.find(x=>x.code===a[2]); if(f){ sendGesture(f.code,'fareAid',f.name||fmtCode(f.code)); say('Jʼy vais ! Aider à bâtir, cʼest bâtir un peu chez soi aussi.'); } } else if(a[1]==='cst'){ openVoyage(); } else if(a[1]==='later'){ store.set('cstAsk',Date.now()); } }
function openIsland(){ const k=store.get('skyI',[]);
  openSheet(revaHead('Lʼîle vue dʼen haut')+`<p>Dʼici, on voit comment lʼîle est faite. Touche un nom.</p><div class="imap"><svg viewBox="0 0 200 200" aria-hidden="true"><rect width="200" height="200" fill="#2E86C1"/><ellipse cx="100" cy="92" rx="88" ry="74" fill="#7FD6DE"/><path d="M14 104 A88 74 0 1 1 30 142" fill="none" stroke="#FFF7E0" stroke-width="5" stroke-dasharray="20 3" stroke-linecap="round"/><path d="M40 92 Q44 54 80 50 Q104 34 128 52 Q160 56 160 96 Q156 134 110 138 Q60 142 40 92Z" fill="#F1DDB0"/><path d="M52 92 Q56 64 84 60 Q104 48 124 62 Q148 66 148 96 Q144 124 108 126 Q64 128 52 92Z" fill="#3B8C58"/><path d="M78 96 L92 74 L100 86 L110 68 L124 96Z" fill="#2A6B45"/><path d="M92 100 Q78 112 62 118 Q44 126 30 140" fill="none" stroke="#2E86C1" stroke-width="2.4"/><ellipse cx="168" cy="150" rx="11" ry="6" fill="#F1DDB0"/><ellipse cx="168" cy="149" rx="6" ry="3" fill="#3B8C58"/></svg>${ISL.map(o=>`<button data-i="${o.id}" class="${k.includes(o.id)?'good':''}" style="left:${o.x}%;top:${o.y}%">${o.n}</button>`).join('')}</div><div id="isInfo" aria-live="polite"><p class="small muted">${k.length} sur ${ISL.length} connus. Le côté dʼoù vient le vent reçoit plus de pluie : il est plus vert. Lʼautre côté, « sous le vent », est plus sec.</p></div><button class="btn primary" id="isEnd">Terminer</button>`);
  $('#sx').onclick=closeSheet; sheetInner.querySelector('.imap').addEventListener('click', e=>{ const b=e.target.closest('[data-i]'); if(!b) return; const o=ISL.find(x=>x.id===b.dataset.i), kk=store.get('skyI',[]); if(!kk.includes(o.id)){ kk.push(o.id); store.set('skyI',kk); } sheetInner.querySelectorAll('.imap button').forEach(x=>x.classList.toggle('on',x===b)); b.classList.add('good'); $('#isInfo').innerHTML=`<div class="card flat"><div class="eyebrow">${o.n} · ${o.fr}</div><p class="small">${o.d}</p></div><div class="note">${o.h}</div>`; });
  $('#isEnd').onclick=()=>{ const kk=store.get('skyI',[]), all=ISL.every(o=>kk.includes(o.id)), first=all && revaReward('island'); revaReward(); closeSheet(); if(first) say('Tu connais lʼîle par cœur : une pirogue glisse maintenant sur le lagon. Et on peut bâtir un fare. (+5 plumes)'); }; }
function revaAllDone(){ const R=revaDone(); return !!(R.clouds && R.winds && R.island && fareGet().n>=4); }
function cstGet(){ const o=store.get('cst',null); return (o && typeof o==='object') ? o : {done:false, share:false, up:false, day:''}; }
function hardLately(){ try{ const now=Date.now(), days=new Set(); log.forEach(l=>{ if(now-l.ts<7*864e5){ const e=EMO.find(x=>x.id===l.emo); if(e && e.cat==='hard') days.add(dayKey(l.ts)); } }); return days.size>=3; }catch(e){ return false; } }
function revaMore(){ const R=revaDone(), F=fareGet(), C=cstGet(), ki=store.get('skyI',[]); let h='';
  if(R.clouds && R.winds) h+=`<button class="btn" id="rvI" style="display:block;width:100%;text-align:left;line-height:1.35;margin-top:10px"><b>Lʼîle vue dʼen haut</b>${R.island?' ✓':''}<br><span class="small muted">${ki.length} sur ${ISL.length} lieux connus.</span></button>`;
  if(R.island) h+=`<button class="btn" id="rvF" style="display:block;width:100%;text-align:left;line-height:1.35;margin-top:10px"><b>${F.n>=4?'Te fare':'Bâtir un fare'}</b>${F.n>=4?' ✓':''}<br><span class="small muted">${F.n>=4?'Ton lieu sûr.':'Étape '+(F.n+1)+' sur 4, une par jour.'}</span></button>`;
  if(revaAllDone()) h+=`<button class="btn" id="rvV" style="display:block;width:100%;text-align:left;line-height:1.35;margin-top:10px"><b>${C.done?'Les étoiles de '+esc(cfg.name):'Le grand vol'}</b><br><span class="small muted">${C.done?(C.up?esc(cfg.name)+' est dans le ciel. Tu peux lʼappeler.':'Revoir le chemin, ou laisser '+esc(cfg.name)+' remonter.'):esc(cfg.name)+' a quelque chose à te proposer. Quand tu veux.'}</span></button>`;
  return h; }
function revaMoreWire(){ if($('#rvI')) $('#rvI').onclick=openIsland; if($('#rvF')) $('#rvF').onclick=openFare; if($('#rvV')) $('#rvV').onclick=()=>{ const C=cstGet(); if(C.done) openStars(); else openVoyage(); }; }
let VY={i:0};
function openVoyage(){ VY={i:0}; voyStep(); }
function voyStep(){ const nm=esc(cfg.name), C=cstGet(); let h='';
  const days=[...new Set(log.map(l=>dayKey(l.ts)))], first=log.length?new Date(Math.min.apply(null,log.map(l=>l.ts))):new Date();
  const nav=(next,label)=>`<div class="row"><button class="btn ghost" id="vyNo">Pas encore</button><button class="btn primary" id="vyNext">${label||'Continuer'}</button></div>`;
  if(VY.i===0) h=revaHead('Le grand vol')+`<p>Tu as fait grandir les quatre lieux, ouvert le ciel, appris les nuages et les vents, bâti un fare.</p><p>Je crois que tu sais maintenant faire seul·e ce que je te demandais chaque jour : tʼarrêter, et regarder le temps quʼil fait en toi.</p><p class="small muted">Avant de te proposer quelque chose, jʼaimerais quʼon regarde le chemin ensemble. Rien ne sera effacé, et tu peux dire « pas encore » à tout moment.</p>`+nav(1,'Regarder le chemin');
  else if(VY.i===1){ const strip=log.slice(-120).map(l=>{ const e=EMO.find(x=>x.id===l.emo); return `<span style="background:${e?e.color:'#CFD8DE'}"></span>`; }).join('');
    h=revaHead('Tes jours')+`<p>Depuis le ${first.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}, tu es venu·e <b>${days.length} jour${days.length>1?'s':''}</b> dire comment tu te sentais.</p><div class="retro" aria-hidden="true">${strip}</div><p class="small muted">Chaque carré est un moment. Il y a de tout, et cʼest exactement ça, un cœur vivant : aucune couleur nʼest restée pour toujours.</p>`+nav(); }
  else if(VY.i===2){ const ids=[...new Set(log.map(l=>l.emo))], ws=ids.map(id=>EMO.find(x=>x.id===id)).filter(Boolean); let sh=[]; try{ shells.forEach(x=>x.t.forEach(t=>sh.push(t))); }catch(e){} sh=sh.sort(()=>Math.random()-.5).slice(0,3);
    h=revaHead('Tes mots')+`<p>Tu sais nommer <b>${ws.length} émotion${ws.length>1?'s':''}</b>. Ce quʼon sait nommer fait moins peur.</p><div class="chips">${ws.map(e=>`<span style="border-color:${e.color}">${e.ty} · ${e.fr}</span>`).join('')}</div>${sh.length?`<div class="card flat"><div class="eyebrow">Trois de tes coquillages</div>${sh.map(t=>`<p class="small" style="margin:4px 0">· ${esc(t)}</p>`).join('')}</div>`:''}`+nav(); }
  else if(VY.i===3){ const got=(garden.got||[]).filter(k=>PLANTS[k]), st=Object.keys(stonesGot()).length, F=fareGet();
    h=revaHead('Ce que tu as bâti')+`<div class="chips"><span>${got.length} plante${got.length>1?'s':''} récoltée${got.length>1?'s':''}</span><span>${st} pierre${st>1?'s':''}</span><span>${friends.length} cœur${friends.length>1?'s':''} lié${friends.length>1?'s':''}</span><span>un fare</span></div><div class="farefig">${fareSVG(4)}</div>${F.help.length?`<p class="small">Bâti avec ${F.help.map(esc).join(', ')}.</p>`:''}<div class="retrow">${[1,3,6].map(g=>`<div>${birdSVG(Object.assign({},cfg,{g}),'vy'+g)}${g===1?'au début':g===3?'en chemin':'aujourdʼhui'}</div>`).join('')}</div><p class="small muted">Rien de tout ça nʼest arrivé en un jour.</p>`+nav(); }
  else if(VY.i===4){ const mut=friends.length>0;
    h=revaHead('Ce que je te propose')+`<p>Jʼaimerais monter dans le ciel de nuit et devenir un groupe dʼétoiles, pour montrer le chemin aux manu plus jeunes.</p><div class="card flat" style="border-color:var(--lagoon)"><p class="small"><b>Je ne pars pas.</b> Tu pourras mʼappeler quand tu veux et je redescendrai aussitôt. Tout reste ouvert : le faʻaʻapu, les lieux, tes cœurs liés, tes couleurs.</p><p class="small">Ce qui change : je ne viendrai plus te demander chaque jour comment tu vas. Cʼest toi qui viendras me le dire, si tu en as envie.</p></div>${mut?`<label class="small" style="display:flex;gap:10px;align-items:flex-start;margin:10px 0"><input type="checkbox" id="vyShare" style="width:22px;height:22px;flex:none"> <span>Montrer mes étoiles dans le ciel de nuit de mes cœurs liés. <span class="muted">Sinon, toi seul·e les verras. Tu peux changer dʼavis plus tard.</span></span></label>`:''}<div class="row"><button class="btn ghost" id="vyNo">Pas encore</button><button class="btn primary" id="vyUp">Monter dans le ciel</button></div>`; }
  else { h=revaHead('Lʼaventure du vrai monde')+`<p>Ce que tu as appris ici marche aussi dehors. Trois idées, tu choisis :</p><div class="card flat"><p class="small"><b>Quelquʼun.</b> Cette semaine, dis à une vraie personne comment tu te sens, avec tes mots à toi.</p></div><div class="card flat"><p class="small"><b>Un lieu.</b> La rivière, la plage, la montagne existent pour de vrai. Va en voir un, et lis le ciel au passage.</p></div><div class="card flat"><p class="small"><b>Un geste.</b> Dire non sans se fâcher, demander pardon, aider à bâtir : essaie-en un, en vrai.</p></div><p class="small muted">Et si un jour ça ne va pas, je suis là, et le bouton Aide aussi.</p><button class="btn primary" id="vyEnd">Māuruuru, ${nm}</button>`; }
  openSheet(h); sheetInner.scrollTop=0; $('#sx').onclick=closeSheet;
  if($('#vyNo')) $('#vyNo').onclick=()=>{ store.set('cstAsk',Date.now()); closeSheet(); say('Dʼaccord. On a tout le temps. Je reste là.'); };
  if($('#vyNext')) $('#vyNext').onclick=()=>{ VY.i++; voyStep(); };
  if($('#vyUp')) $('#vyUp').onclick=()=>{ const sh=!!($('#vyShare') && $('#vyShare').checked); closeSheet(); cstRise(sh); };
  if($('#vyEnd')) $('#vyEnd').onclick=()=>{ closeSheet(); }; }
const CST_P=[[0,0],[16,-10],[30,-4],[40,-18],[14,8],[-14,6],[-30,16]], CST_L=[[0,1],[1,2],[2,3],[1,4],[0,5],[5,6],[4,0]];
function cstSVG(cx,cy,s,col){ let h=''; CST_L.forEach(l=>{ const a=CST_P[l[0]], b=CST_P[l[1]]; h+=`<line x1="${cx+a[0]*s}" y1="${cy+a[1]*s}" x2="${cx+b[0]*s}" y2="${cy+b[1]*s}" stroke="${col}" stroke-opacity=".5" stroke-width="1.1"/>`; }); CST_P.forEach((p,i)=>{ const r=(i===3?2.6:1.8)*Math.max(.7,s); h+=`<circle cx="${cx+p[0]*s}" cy="${cy+p[1]*s}" r="${r*2.4}" fill="${col}" opacity=".16"/><circle cx="${cx+p[0]*s}" cy="${cy+p[1]*s}" r="${r}" fill="${col}"/>`; }); return h; }
function cstRise(share){ const d=document.createElement('div'); d.className='cstfx'; d.setAttribute('role','dialog'); d.setAttribute('aria-label',cfg.name+' monte dans le ciel et devient un groupe dʼétoiles');
  d.innerHTML=`<svg viewBox="0 0 360 440">${Array.from({length:40},(_,i)=>`<circle cx="${(i*89)%360}" cy="${(i*53)%440}" r="${.6+(i%3)*.4}" fill="#fff" opacity="${.2+(i%4)*.1}"/>`).join('')}<g transform="translate(120 100)"><g class="cb"><svg width="120" height="110" x="0" y="0">${birdSVG(cfg,'cst').replace(/^<svg[^>]*>/,'<g>').replace(/<\/svg>\s*$/,'</g>')}</svg></g></g>${CST_P.map((p,i)=>`<g class="cs" style="animation-delay:${4+i*.35}s"><circle cx="${180+p[0]*3}" cy="${160+p[1]*3}" r="9" fill="#FFE2A8" opacity=".2"/><circle cx="${180+p[0]*3}" cy="${160+p[1]*3}" r="${i===3?4.6:3.4}" fill="#FFE2A8"/></g>`).join('')}<g class="cl">${CST_L.map(l=>{ const a=CST_P[l[0]], b=CST_P[l[1]]; return `<line x1="${180+a[0]*3}" y1="${160+a[1]*3}" x2="${180+b[0]*3}" y2="${160+b[1]*3}" stroke="#CFE0FF" stroke-opacity=".6" stroke-width="1.4"/>`; }).join('')}</g><text class="ct" x="180" y="300" font-size="24" font-weight="700">Te fetiʻa o ${esc(cfg.name)}</text><text class="ct" x="180" y="328" font-size="14">Les étoiles de ${esc(cfg.name)}. Elles seront là chaque nuit.</text><text class="ct" x="180" y="372" font-size="12" opacity=".8">Touche pour continuer</text></svg>`;
  document.body.appendChild(d); requestAnimationFrame(()=>d.classList.add('on')); document.body.classList.add('manu-up');
  let ready=false; setTimeout(()=>{ ready=true; }, RM?800:8600);
  const end=()=>{ if(d.dataset.done) return; d.dataset.done='1'; store.set('cst',{done:true, share:!!share, up:true, day:dayKey(Date.now())}); d.classList.remove('on'); setTimeout(()=>{ d.remove(); try{ renderNight(); pushHeart(); }catch(e){} cstUpRender(); VY.i=5; voyStep(); },900); };
  d.addEventListener('click',()=>{ if(ready) end(); }); setTimeout(end, RM?8000:22000); }
function cstUpRender(){ const C=cstGet(), up=!!(C.done && C.up); document.body.classList.toggle('manu-up',up); const q=$('#quiet'); if(!q) return; let b=$('#callManu');
  if(up && !b){ b=document.createElement('button'); b.id='callManu'; b.className='btn primary callmanu'; b.onclick=()=>cstCall(); q.appendChild(b); } if(b){ b.hidden=!up; b.textContent='Appeler '+cfg.name; } }
function cstCall(){ const C=cstGet(); C.up=false; store.set('cst',C); cstUpRender(); try{ renderNight(); }catch(e){} setTimeout(()=>say('Me voilà. Je nʼétais pas loin : juste au-dessus.'),500); }
function openStars(){ const C=cstGet(), nm=esc(cfg.name);
  openSheet(revaHead('Les étoiles de '+nm)+`<div class="farefig" style="background:linear-gradient(#0B1533,#1B2A5C)"><svg viewBox="0 0 320 170">${cstSVG(160,90,2.2,'#FFE2A8')}</svg></div><p class="small">Elles brillent dans ton ciel de nuit${C.share?', et dans celui de tes cœurs liés':''}. ${C.up?nm+' est là-haut en ce moment.':nm+' est près de toi en ce moment.'}</p>
    <label class="small" style="display:flex;gap:10px;align-items:flex-start;margin:10px 0"><input type="checkbox" id="stShare" ${C.share?'checked':''} style="width:22px;height:22px;flex:none"> <span>Montrer mes étoiles dans le ciel de nuit de mes cœurs liés.</span></label>
    <button class="btn primary" id="stTog">${C.up?'Appeler '+nm:'Laisser '+nm+' remonter'}</button><button class="btn" id="stRetro">Revoir le chemin</button>`);
  $('#sx').onclick=closeSheet; $('#stShare').onchange=e=>{ const c=cstGet(); c.share=e.target.checked; store.set('cst',c); try{ pushHeart(); }catch(x){} toast(c.share?'Tes étoiles sont visibles chez tes cœurs liés':'Tes étoiles ne sont visibles que chez toi'); };
  $('#stTog').onclick=()=>{ const c=cstGet(); closeSheet(); if(c.up) cstCall(); else { c.up=true; store.set('cst',c); cstUpRender(); toast(cfg.name+' est remonté dans ses étoiles'); } };
  $('#stRetro').onclick=()=>{ VY={i:1, again:true}; voyStep(); }; }
function cstTick(){ try{ const C=cstGet(); if(C.done || !revaAllDone() || hardLately()) return; if(Date.now()-(store.get('cstAsk',0)||0) < 7*864e5) return; if(!visitFree() || bubbleEl.classList.contains('show') || document.querySelector('.portal')) return; store.set('cstAsk',Date.now()); sayHTML(`Jʼai quelque chose à te proposer. Rien ne presse.<div class="mini"><button data-m="vy:cst">Écouter</button><button data-m="vy:later">Pas encore</button></div>`, 40000); }catch(e){} }
{ const _ni=nightInner; nightInner=function(){ let h=_ni.apply(this,arguments); try{ const C=cstGet(); if(C.done) h+=cstSVG(150,228,1.25,'#FFE2A8')+`<text x="150" y="266" text-anchor="middle" font-size="9" fill="#FFE2A8" opacity=".8" font-family="sans-serif">${esc(cfg.name)}</text>`;
      let n=0; friends.forEach(f=>{ const d=FR[f.code]; if(n<3 && d && d!=='err' && d.cfg && d.cfg.star===true && isMutual(f.code)){ const y=362+n*62; h+=cstSVG(300,y,.8,'#CFE0FF')+`<text x="300" y="${y+24}" text-anchor="middle" font-size="8" fill="#CFE0FF" opacity=".8" font-family="sans-serif">${esc(String(d.name||f.name||'').slice(0,12))}</text>`; n++; } }); }catch(e){} return h; };
  const _ml=myLook; myLook=function(){ const o=_ml.apply(this,arguments); try{ const C=cstGet(); if(C.done && C.share) o.star=true; }catch(e){} return o; };
  const _ar=askRing; askRing=function(auto){ try{ if(auto===true && cstGet().done) return; }catch(e){} return _ar.apply(this,arguments); };
  const _rs=revaScene; revaScene=function(){ let h=_rs.apply(this,arguments); try{ const R=revaDone(), F=fareGet(); if(R.island) h+='<g class="sc-bob"><path d="M118 478 q14 7 30 0 l-3 5 h-24z" fill="#8A5A2B"/><path d="M132 478 V462 l10 12z" fill="#FFF7E0"/><path d="M124 486 h18" stroke="#8A5A2B" stroke-width="1.2"/></g>'; if(F.n>=4) h+='<g transform="translate(196 462)"><path d="M-9 0 L0 -8 L9 0Z" fill="#C9A24A" stroke="#8A6A2B" stroke-width=".8"/><rect x="-6" y="0" width="12" height="6" fill="#E9D3A0"/><rect x="-1.5" y="2" width="3" height="4" fill="#6B4A2A"/></g>'; }catch(e){} return h; }; }
setTimeout(()=>{ try{ cstUpRender(); if(typeof qActs==='function' && typeof QI!=='undefined'){ QI.ile='<circle cx="14" cy="14" r="11" fill="#7FD6DE" stroke="#FFF7E0" stroke-width="1.6" stroke-dasharray="5 2"/><path d="M8 16 Q9 9 14 10 Q20 8 20 15 Q16 20 8 16Z" fill="#3B8C58"/>'; QI.fare='<path d="M4 15 L14 6 L24 15Z" fill="#C9A24A" stroke="#8A6A2B" stroke-width="1"/><rect x="7" y="15" width="14" height="8" fill="#E9D3A0" stroke="#8A6A2B" stroke-width="1"/><rect x="12" y="17" width="4" height="6" fill="#6B4A2A"/>'; QI.etoile='<rect x="2" y="2" width="24" height="24" rx="7" fill="#1B2A5C"/><g fill="#FFE2A8"><circle cx="8" cy="18" r="1.6"/><circle cx="13" cy="13" r="1.6"/><circle cx="18" cy="15" r="1.6"/><circle cx="21" cy="8" r="2.2"/></g><path d="M8 18 L13 13 L18 15 L21 8" stroke="#CFE0FF" stroke-width=".8" fill="none"/>';
      const _qa2=qActs; qActs=function(){ const a=_qa2.apply(this,arguments); if(curPlace==='reva'){ const R=revaDone(); if(R.clouds&&R.winds) a.push({k:'ile',l:'Lʼîle',t:'Lʼîle vue dʼen haut',go:openIsland}); if(R.island) a.push({k:'fare',l:'Fare',t:'Te fare',go:openFare}); if(revaAllDone()) a.push({k:'etoile',l:cstGet().done?'Étoiles':'Envol',t:'Le grand vol',go:()=>{ cstGet().done?openStars():openVoyage(); }}); } return a; }; dockRender(); } }catch(e){} cstTick(); },120);
setInterval(cstTick,45000);

"""
    rep("/* ---------- install button ---------- */", new+"/* ---------- install button ---------- */")
    # le regard des amis : garder "star"
    rep("fx:c.fx===true};","fx:c.fx===true}; if(c.star===true) o.star=true;")
    open(path,'w',encoding='utf8').write(s)
    print('ok',path)
